### ISSUE TITLE
Less

### ISSUE THREAD

**Issue by kevsmt** [jasonlewis/basset#1]
Hi can u add a lessphp implementation? thanks!

**Comment by jasonlewis** [comment]
I just scanned over the Less PHP docs and this should be entirely possible. I was originally going to look at a LESS implementation. Thanks for this. I'll look into it.

**Comment by kevsmt** [comment]
heads-up info btw man, lessphp is not fully supports lesscss.org (JS) syntax/implementation there are some issues that are not compatible at the moment...

**Comment by jasonlewis** [comment]
Yeah I saw there were a few compatibility issues. Regardless you should be able to use the client-side implementation of LESS currently. I haven't tested with the server-side version but I have no reason to see why it shouldn't work as files are still called with a .css extension and displayed with a text/css content type.

Although for people that don't have LESS installed this LessPHP implementation will be great!

**Comment by kevsmt** [comment]
yeah, i use this for the moment

```
Asset::style('functions-less', 'assets/frontend/less/functions.less', 'less', array('rel' => 'stylesheet/less'));
```

also if possible please add a attribute options in your Basset::add method, so we can customize it more like:

```
Basset\Basset::add('functions-less', 'assets/frontend/less/functions.less', 'less', array('rel' => 'stylesheet/less'));
```

Cheers man! nice module :) keep it up..

**Comment by jasonlewis** [comment]
Basset uses the HTML::style() method for generating links to stylesheets like that so the rel attribute should already be set.

Example:

```
echo Basset\Basset::add('styles', 'path/to/styles.css')->styles();
```

Would produce:

```
<link rel="stylesheet" type="text/css" href="http://website/path/to/styles.css" />
```

If there is more need for attributes to be passed in I'll look at adding something in. For stylesheets I may add the option of specifying the target media though as I can see that being required in some places.

**Comment by kevsmt** [comment]
yep definitely: for less it uses though `rel="stylesheet/less"` and probably for onilabs apollo, uses `type="text/sjs"` its good to have it already there than need it when it doesn't..

**Comment by jasonlewis** [comment]
Yeah good point. I'll put this in as a todo as well for 1.1. :)

**Comment by kevsmt** [comment]
thanks man ;)

**Comment by jasonlewis** [comment]
LESS compatibility is now available in v1.1

**Comment by kevsmt** [comment]
Thanks Man! ;)

**Comment by jasonlewis** [comment]
Not a problem. When using LESS it automatically detects it and uses the correct attributes too.

```
echo Basset::add('less_stylesheet', 'less_stylesheet.less');
```

Will return:

```
<link rel="stylesheet/less" type="text/css" href="http://website/path/to/less_stylesheet.less" />
```

Enjoy.
