### ISSUE TITLE
Basset\Config::set() should not be called statically

### ISSUE THREAD

**Issue by tcql** [jasonlewis/basset#10]
The set() method of the latest Basset\Config class is not defined as static, even though it is called statically. This results in : 
Non-static method Basset\Config::set() should not be called statically, assuming $this from incompatible context

**Comment by jasonlewis** [comment]
Cheers, I'll push a fix when I get near a computer. Send a pull if you can.
:)
On May 24, 2012 3:49 AM, "tchannel" <
reply@reply.github.com>
wrote:
