### ISSUE TITLE
How to set a filter's options (e.g. UglifyJS2) 

### ISSUE THREAD

**Issue by ghost** [jasonlewis/basset#102]
Hey Jason, I'm not sure where to ask this, since I know we're not supposed to post L4 help topics in the forums. But...

How do you set options for a filter? Is it possible?

E.g. I'm using UglifyJS2 and trying to turn on its "mangle" option. 

```
'filters' => array(
    'UglifyJs2Filter' => array(
        'UglifyJs2Filter' => array('/usr/local/bin/uglifyjs')
    )
)
```

Assetic/Filters/UglifyJs2Filter.php contains a public method to turn it on using setMangle(), but I'm not sure if/how Basset can access that because trying something like `$collection->add('js/vendor/handlebars.js')->apply('UglifyJs2Filter')->setMangle(true);` doesn't work.

(I'm using Basset's master branch. UglifyJS2 is working great with Basset. Just not sure how to set the filter's options. Should I just wait for Basset's develop branch updates?)

**Comment by jasonlewis** [comment]
This isn't possible on the master branch at the moment, only on the develop branch. Hopefully I'll be able to merge the develop branch across soon. For now, if you'd like, you can use the develop branch by using `dev-develop` in your `composer.json`.

You can access and manipulate the filters public methods with a `beforeFiltering()` method.

On the develop branch your alias would look like this:

``` php
'filters' => array(
    'UglifyJs2Filter' => array('UglifyJs2Filter', function($filter)
    {
        $filter->setArguments('/usr/local/bin/uglifyjs');
        $filter->beforeFiltering(function($filter)
        {
            $filter->setMangle(true);
        });
    })
)
```

Inside the `beforeFiltering()` you receive an instance of the instantiated filter before the filtering process takes place.

**Comment by ghost** [comment]
Thank you. Very helpful! That is going to be awesome.
