### ISSUE TITLE
Protocol-relative URLs don't work

### ISSUE THREAD

**Issue by greggilbert** [jasonlewis/basset#103]
It's currently not possible to add a protocol-relative URL asset like this:

```
'aliases' => array(
    'assets' => array(      
        'jquery' => '//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js',
    ),
),
```

It'd be useful to be able to have these sort of assets for aliases that may live in both HTTP and HTTPS situations.

**Comment by jasonlewis** [comment]
I've just pushed some new stuff to develop which should allow protocol relative URLs.
