### ISSUE TITLE
requireTree does not maintain proper inclusion order

### ISSUE THREAD

**Issue by iricketson** [jasonlewis/basset#105]
Using Basset4

For example:

``` php

$collection->requireTree('backbone/apps')->apply('CoffeeScript');
$collection->add('backbone/app.coffee')->apply('CoffeeScript');

```

For some reason all the files included by requireTree are included AFTER the single file included through the add() method.

**Comment by jasonlewis** [comment]
I'll take a look at this. Thanks.

**Comment by jasonlewis** [comment]
All assets added now maintain the order that they were added (unless manually overwritten).
