### ISSUE TITLE
Dependency conflict with laravel/framework

### ISSUE THREAD

**Issue by betawax** [jasonlewis/basset#107]
The L4 Basset composer.json seems to conflict with the one from laravel/framework and keeps Laravel from updating to the newest version. It must be the `symfony/process` requirement, which is

```
"symfony/process": "2.2.*"
```

on jasonlewis/basset, but

```
"symfony/process": "2.3.*",
```

on laravel/framework.

https://github.com/laravel/framework/commit/472c93945305ec7122f0f6e2afb30cb2d663d4c6

**Comment by Anahkiasen** [comment]
I don't think this is even needed as that dependency will be checked out by Laravel itself anyway and Basset can't be used outside of Laravel (at least I think so ?).

**Comment by jasonlewis** [comment]
This component is used by Basset to detect filter constructor arguments and find the correct executables.

Just merged in the update.

**Comment by betawax** [comment]
Fast as always, thanks @jasonlewis! :+1:

**Comment by Anahkiasen** [comment]
> This component is used by Basset to detect filter constructor arguments and find the correct executables.

Yeah I know, but Basset doesn't _need_ it in its Composer file as Laravel will always check it out anyway so it will always be present in the vendor folder, whether Basset manually requires it or not.

**Comment by jasonlewis** [comment]
Just for tests. :smile:

**Comment by Anahkiasen** [comment]
Then it's a `require-dev` dependency, not a `require` dependency :°

**Comment by jasonlewis** [comment]
Yeah I suppose it is then. :grinning:

I'll shift em over.

**Comment by Anahkiasen** [comment]
MY WORK HERE IS DONE.

/overly-picky man flies away

**Comment by jasonlewis** [comment]
:laughing: 

Cheers @Anahkiasen!
