### ISSUE TITLE
[Request] Allow data attributes in script tags

### ISSUE THREAD

**Issue by betawax** [jasonlewis/basset#111]
Some JavaScripts, like the Aloha Editor, require data attributes in script tags:

``` html
<script src="//cdn.aloha-editor.org/latest/lib/aloha.js" data-aloha-plugins="common/ui, common/format, common/list, common/link, common/highlighteditables"></script>
```

Source: http://aloha-editor.org/#howto

This seems to be not possible at the moment.

**Comment by jasonlewis** [comment]
Hm, in this particular instance you're using a remote asset. What effect would this have if you were to apply these attributes to say, a built collection? I'm just wondering on the best way to do this, at the moment I'm thinking in the collection itself.

My only concern is that if I allow for this on a per-asset basis then the attributes will probably be wiped when you build a collection (except for the remote assets of course). Does that make sense?

**Comment by betawax** [comment]
Your concerns are entitled, I didn't think of local assets because Aloha was the first and only JS I ever had to use a data attribute on the script tag and I always prefer CDN assets if possible.

As the Aloha Editor requires you to include three different JS files (it's a mess), specifying the attribute for the whole collection would not work I guess. It must be on a per asset base.

Maybe a solution would be to check if a single asset in an collection has a data attribute specified and if so, automatically build a separate collection for this asset?

As this issue seems to be a rare case, I'm not sure if it's really worth the time to find a solution for it. Maybe it's better to wait if more people run into this issue...

**Comment by jasonlewis** [comment]
Look for now I'd say strip it from the collection and require that script manually. I'll think about this though. I think if I do implement it then any assets that have attributes specified on them will be excluded from the build.

**Comment by betawax** [comment]
Sounds good to me. :+1:
