### ISSUE TITLE
Can't use dev-develop or merged "Dependency conflict"

### ISSUE THREAD

**Issue by johannesfosseus** [jasonlewis/basset#113]
Hi Jason

I'm trying to checkout "dev-develop" to avoid problems on the "symfony/process": "2.3.*" dependency problems.

But Composer update fails and return "fatal: reference is not a tree: f0b4273c954365bef0eb4401c6157da20c80507".

Are there any other way I can use the latest fix for the L4 dependency problems? Seems like the merge is not in the "dev-master" yet.

https://github.com/jasonlewis/basset/issues/107

all the best // Johannes

**Comment by jasonlewis** [comment]
Fix pushed. Thanks.
