### ISSUE TITLE
Remove symfony/process

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#114]
This causes Composer to install an older beta of Laravel. As this is a package that is installed by the Illuminate components anyway I'd suggest removing it entirely to always be up to date to what they require.

**Comment by syphernl** [comment]
Also see #107

**Comment by jasonlewis** [comment]
It's now a dev dependencies @Anahkiasen, so tests can still be run. Cheers, sorry for the stupid push. :grinning:
