### ISSUE TITLE
Reimplement the Basset::show method

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#117]
I don't really see why this was removed, a facade is _far_ cleaner than some functions in the global namespace, and feel kind of inelegant in the middle of the code. Could the Facade be at least brought back ?

**Comment by barryvdh** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by johannesfosseus** [comment]
+1

**Comment by jasonlewis** [comment]
Just pushed the re-implementation. The syntax is much the same, but it can take a mixed number of arguments.

``` php
{{ Basset::show('application.css', 'admin.css');
```

The facade also exists at `Basset\Facade`, so alias that to `Basset`.

``` php
'aliases' => array(

    'Basset' => 'Basset\Facade'

)
```
