### ISSUE TITLE
Disable Basset Routing

### ISSUE THREAD

**Issue by kfriend** [jasonlewis/basset#119]
Is there any way to disable Basset's routing of assets? I believe the older version had a "handles" config item (may be wrong about the name) which designated whether Basset would route assets.

**Comment by jasonlewis** [comment]
Basset will dynamically route to the assets when there isn't a built collection, for either the production or development environment. Take a look at the [serving workflow](http://jasonlewis.me/code/basset/4.0/serving) of Basset.

**Comment by Anahkiasen** [comment]
Isn't there any way in local to just route to the assets themselves to speed it up ? Since when using the current route it still makes an additional Laravel request which takes some time to boot up for nothing.

**Comment by jasonlewis** [comment]
My idea was that majority of people would just build a development collection. I'm planning on implementing a `watch` feature so that the collection is re-built when changes are detected.

**Comment by kfriend** [comment]
How about segmenting the routing functionality into another service provider?

**Comment by jasonlewis** [comment]
I think I'm missing the point. Why do you need to disable the routing and why would it be moved into another service provider?

**Comment by andrew13** [comment]
The problem for me with the development collections is that the relative image path within my css breaks.

```
http://starter.local/assets/compiled/admin-css/assets/css/wysihtml5/bootstrap-wysihtml5-0.0.2.css
```

Contains relative paths to images. Since it is in development and using the new path it is breaking the image paths. In my opinion, It would be very useful if during development it just returns the original asset.

Another option, if Laravel is in debug mode, display the original files.

**Comment by andrew13** [comment]
Of course if you just display the original files and they are LESS or SASS files that won't work. Maybe setting the compiled files into the main compiled directory would be a good idea.

**Comment by jasonlewis** [comment]
Andrew, your relative paths should be fixed if you use the
UriRewriteFilter. I've actually got some changes that I'll push today that
fix a number of issues.

**Comment by jasonlewis** [comment]
Basset will no longer dynamically serve assets.

**Comment by Anahkiasen** [comment]
Well yes it still does, even in a local environment, after deleting the `builds` folder, the manifest and all, Basset still re-copies the assets in `builds` and routes to them, live.
It works but it's not what I want. What I want is – in dev environment – for Basset to directly point to the actual assets so that my dev workflow with LiveReload and such isn't completely broken.

**Comment by jasonlewis** [comment]
It does that so that it can apply any filters to assets. Basset isn't a one size fits all, I hope you know that.

**Comment by Anahkiasen** [comment]
No no I know but I mean, there should be an additional `dev` or `local` key in the config, same as the `production` one, with environments in which you want the root assets. An option of some kind, I don't know how you could put that but I feel this is pretty important – being completely cut off from the actual assets disable a lot of front-end helpers.

**Comment by jasonlewis** [comment]
So you want to be able to link to the raw assets? Untouched.

**Comment by Anahkiasen** [comment]
Pretty much yeah. Maybe it's even already possible, just couldn't find how.

**Comment by jasonlewis** [comment]
Nah not possible. But it shouldn't be too hard to do. I'll get this in. :smile:

**Comment by andrew13** [comment]
Awesome! :+1:

**Comment by xDragonZ** [comment]
looking forward the ability to disable basset in dev mode.

**Comment by fishactual** [comment]
Also looking forward to this ability.

**Comment by Anahkiasen** [comment]
Well this is done actually, with the `->raw()` and `->rawOnEnvironment()` methods.
