### ISSUE TITLE
Image load from CSS

### ISSUE THREAD

**Issue by robertomello** [jasonlewis/basset#120]
Hi, i'm having issues to load a img from css file.

I'm working with datatables.net. The JS and CSS are loaded well. But i cannot get the right path to load the images?

Thank you
Roberto

**Comment by jasonlewis** [comment]
Most likely you'll need to use the `UriRewriteFilter` if you aren't already. Can you post your collection definition here please.

**Comment by robertomello** [comment]
Hi, thank you for the very fast reply :)

Well, i'm starting now with Laravel and Basset so the collection is very basic

``` php

    'collections' => array(
        'application' => function($collection) {
            $collection->directory('assets/css', function($collection) {
                        $collection->add('bootstrap.min.css');
                        $collection->add('bootstrap-responsive.min.css');
                        $collection->add('style.css');
                    });
            $collection->directory('assets/js', function($collection) {
                        $collection->add('jquery.v1.9.1.min.js');
                        $collection->add('bootstrap/bootstrap.min.js');
                    });
        },
        'datatables' => function($collection) {
            $collection->directory('assets/css/datatables', function($collection) {
                        $collection->add('jquery.dataTables.css');
                    });
            $collection->directory('assets/js', function($collection) {
                        $collection->add('jquery.dataTables.min.js');
                    });
        }
```

And here is the code of original css file:

``` css
.sorting { background: url('../images/sort_both.png') no-repeat center right; }
```

**Comment by jasonlewis** [comment]
Yes so you need to applying the `UriRewriteFilter` so that relative image paths are rewritten to be absolute.

Simply apply the filter to either the entire CSS directory or on the individual asset. Generally you don't need to adjust the filter, unless you're running the application in a subdirectory.

``` php
$collection->add('jquery.dataTables.css')->apply('UriRewriteFilter');
```

**Comment by robertomello** [comment]
Wonderfull, all works fine!

Thank you very much!

**Comment by andrew13** [comment]
Perfect! Thanks. I'd add this to the documentation :+1:

**Comment by andrew13** [comment]
I used the filter like:

```

    'collections' => array(

        'public-css' => function($collection)
        {
            $collection->directory('assets/css', function($collection)
            {
                $collection->add('bootstrap.min.css');
                $collection->add('bootstrap-responsive.min.css');
                $collection->add('style.css');
            })->apply('UriRewriteFilter');
        },
        'public-js' => function($collection)
        {
            $collection->directory('assets/js', function($collection)
            {
                $collection->add('jquery.v1.8.3.min.js');
                $collection->add('bootstrap/bootstrap.min.js');
            })->apply('UriRewriteFilter');
        },
        'admin-css' => function($collection)
        {
            $collection->directory('assets/css', function($collection)
            {
                $collection->add('bootstrap.min.css');
                $collection->add('wysihtml5/prettify.css');
                $collection->add('bootstrap-responsive.css');
                $collection->add('wysihtml5/bootstrap-wysihtml5-0.0.2.css');
                $collection->add('style.css');
            })->apply('UriRewriteFilter');
        },
        'admin-js' => function($collection)
        {
            $collection->directory('assets/js', function($collection)
            {
                $collection->add('wysihtml5/wysihtml5-0.3.0.js');
                $collection->add('jquery.v1.8.3.min.js');
                $collection->add('prettify.js');
                $collection->add('bootstrap/bootstrap.min.js');
                $collection->add('wysihtml5/bootstrap-wysihtml5.js');
            })->apply('UriRewriteFilter');
        },
```

and the path it produced was `background-image:url("/public/assets/img/glyphicons-halflings.png");` Note the `public` in the url. That shouldn't be there in my case and is breaking the images.

Am I doing it incorrectly?

**Comment by jasonlewis** [comment]
Sounds like you're application is in a subdirectory? If that's the case you should pass in the first argument to filter and set it to the path of your document root. Usually using the `public_path()` should be sufficient.

``` php
$collection->apply('UriRewriteFilter')->setArguments(public_path());
```

You also don't need to apply the `UriRewriteFilter` to any JS. Just the CSS.

**Comment by karikushi** [comment]
Hi there,

I'm also having a similar issue. I'm new to Laravel 4 and Basset, and am coming into an existing project to do some CSS edits. The CSS is loading all styles properly, except that any images referenced from the CSS file do not load, e.g.

<pre>
background-image: url('../img/projectName/image.png');
</pre>

is outputted as

<pre>
background-image: url('assets/img/projectName/image.png');
</pre>

This looks correct, but inspecting the element in Chrome shows that it is trying to find the image at <code>localhost/assets/img/image.png</code>.

This is a problem because my project is located in <code>localhost/projectName</code>, CSS files are in a <code>localhost/projectName/public/assets/css</code> and images are in <code>localhost/projectName/public/assets/img</code>.

Any help would be super appreciated! Changing to absolute paths in the CSS file is just not an option...

Also, just in case my collections are:

<pre>
'collections' => array(
        'public' => function($collection)
        {
            $collection->directory('assets/css', function($collection)
            {
                $collection->add('bootstrap.css');
                $collection->add('bootstrap-responsive.css');
                $collection->add('global.css');
                $collection->add('select2.css');
                $collection->add('chosen.min.css');
                $collection->add('datatables-bootstrap.css');
                $collection->add('font-awesome/css/font-awesome.css');
            })->apply('UriRewriteFilter')->apply('CssMin');
            $collection->directory('assets/js', function($collection)
            {
                $collection->javascript('//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js');
                $collection->add('bootstrap/bootstrap.js');
                $collection->add('select2.min.js');
                $collection->add('chosen.jquery.min.js');
                $collection->javascript('http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js');
                $collection->add('datatables-bootstrap.js');
                $collection->add('datatables.fnReloadAjax.js');
            })->apply('JsMin');
        },
        'admin' => function($collection)
        {
            $collection->directory('assets/css', function($collection)
            {
                $collection->add('bootstrap.css');
                $collection->add('bootstrap-responsive.css');
                $collection->add('global.css');
                $collection->add('wysihtml5/prettify.css');
                $collection->add('wysihtml5/bootstrap-wysihtml5.css');
                $collection->add('datatables-bootstrap.css');
                $collection->add('colorbox.css');
                $collection->add('jquery-ui-1.10.3.custom.css');
                $collection->add('select2.css');
                $collection->add('font-awesome/css/font-awesome.css');
            })->apply('UriRewriteFilter')->apply('CssMin');
            $collection->directory('assets/js', function($collection)
            {
                $collection->javascript('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js');
                $collection->javascript('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js');
                $collection->add('bootstrap/bootstrap.js');
                $collection->add('wysihtml5/wysihtml5-0.3.0.js');
                $collection->add('wysihtml5/bootstrap-wysihtml5.js');
                $collection->javascript('http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js');
                $collection->add('datatables-bootstrap.js');
                $collection->add('datatables.fnReloadAjax.js');
                $collection->add('jquery.colorbox.js');
                $collection->add('prettify.js');
                $collection->add('jquery.jeditable.min.js');
                $collection->add('handlebars.js');
                $collection->add('select2.min.js');
                $collection->add('jquery.elastic.source.js');
                $collection->add('dropzone.js');
            })->apply('JsMin');
        }
</pre>

**Comment by mnazwan** [comment]
Hi @karikushi,
I'v submitted a pull request to allow URL prefix in UriRewriteFilter.
