### ISSUE TITLE
Remote assets are displayed after local ones

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#123]
I have this collection : 

``` php
Basset::collection('application', function($collection) {

    // Remote assets ------------------------------------------------- /

    $collection->add('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css');
    $collection->add('http://fonts.googleapis.com/css?family=Merriweather:400,300,700,900|Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic');

    $collection->add('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js');
    $collection->add('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js');

    // Application assets -------------------------------------------- /

    $collection->add('app/css/styles.css');
    $collection->add('components/icomoon/style.css');

    $collection->add('app/js/bootstrap.js');
    $collection->add('app/js/scripts.js');
    $collection->add('app/js/dynamic-loading.js');

})->apply('CssMin')->apply('JsMin')->apply('UriRewriteFilter');
```

When in production it is shown like this :

``` html
<link rel="stylesheet" type="text/css" href="http://reaaad.dev/assets/application-da76d5ab3fb76a8b6a84f1d52c224a53.css" />
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" />
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Merriweather:400,300,700,900|Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic" />
```

This breaks a lot of stuff since the local assets override CSS properties from the CDN ones. Shouldn't order be kept ?

**Comment by cmnk** [comment]
Hmm yeah, it'd be nice if remote assets were displayed before any local ones. Not sure how difficult this would be to implement?

Otherwise you could create a second collection 'remote' and load that one first?

``` php
basset_stylesheets('remote', 'application')
```

**Comment by jasonlewis** [comment]
This is somewhat related to another issue (#105) about inclusion order. I've got a fix in place for this but waiting for a merge on the framework first. The only problem is that by default remote assets are excluded from the build process by default. This makes it difficult to maintain the order, as they are either shown first or last.

I think @cmenke's idea is probably the best way of handling this at the moment. Unless you are going to include remote assets in the build.

**Comment by jasonlewis** [comment]
In the most recent push remote assets are now included before any other assets.
