### ISSUE TITLE
Troubles making the UriRewriteFilter work

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#124]
My assets (a stylesheet per example) are in `public/app/css/styles.css`, I'm doing testing on a local vhost, `reaaad.dev`. The only way I've managed to make the UriRewriteFilter works is like this :

``` php
// Get the URL holding public assets (http://reaaad.dev or http://reaaad.com)
$assetRoot = str_replace('http://', '', Config::get('app.url'));
$assetRoot = trim($assetRoot, '/');

Basset::collection(function() {
  // ...
})->apply('UriRewriteFilter')->setArguments($assetRoot, array(
  $assetRoot => App::make('path.public'),
));
```

Is there an easier way ?

**Comment by cmnk** [comment]
There's a bug (see PR #122) in UriRewriteFilter when assets are built with artisan.
You might be having the same issue I had earlier?

IMO you should not need to set any arguments for this to work.

**Comment by jasonlewis** [comment]
This has been fixed with a default `UriRewriteFilter` alias that sets the first argument to the public path.
