### ISSUE TITLE
Move documentation to a repo

### ISSUE THREAD

**Issue by kfriend** [jasonlewis/basset#125]
It would allow us to submit fixes/addition to help you out. For example, on http://jasonlewis.me/code/basset/4.0/serving, the "build development collections" link is broken. It points to the ".dev" version of your domain.

**Comment by andrew13** [comment]
:+1:

**Comment by jasonlewis** [comment]
I'll be working on the docs a lot more now. Will move it to a public repo soon. Thanks for the interest guys. :smile:

**Comment by andrew13** [comment]
Thanks for the product. It's great

**Comment by kfriend** [comment]
:+1:

**Comment by jasonlewis** [comment]
Docs are [available on GitHub](https://github.com/jasonlewis/website/tree/master/docs/basset/4.0) now, they're a part of my sites source. Feel free to PR anything.

**Comment by andrew13** [comment]
Woot!
