### ISSUE TITLE
Manifest file cleanup

### ISSUE THREAD

**Issue by KaneCohen** [jasonlewis/basset#126]
Haven't had much time to investigate how Basset works, but i've noticed that once you build a collection you can't return to dynamic serving mode unless you delete collections.json file in storage directory. Shouldn't `php artisan basset:clean` delete that file too?

**Comment by jasonlewis** [comment]
So you've built a development collection? The clean command simply cleans out duplicate collections that may no longer be in use (due to a newer built collection).

I see what you're getting at though. I might have to work this in another command to reset the builds. Is that what you're after?

**Comment by KaneCohen** [comment]
> I see what you're getting at though. I might have to work this in another command to reset the builds. Is that what you're after?

Yeah, that's probably it.

**Comment by jasonlewis** [comment]
I've given this area a huge overhaul and you now have two new commands (actually switches) available to you.

```
php artisan basset --tidy-up

php artisan basset --delete-manifest
```

`--tidy-up` will delete outdated collections on the filesystem and perform some tidying up on the manifest itself. The `--delete-manifest` switch should be self-explanatory.

Thanks.

**Comment by KaneCohen** [comment]
Thanks, Jason!
