### ISSUE TITLE
[Request] Custom attributes for <link/> <script/>

### ISSUE THREAD

**Issue by radmen** [jasonlewis/basset#127]
Recently I've got into a simple problem - I wanted to display stylesheets with `media="print"`.

It's not possible to do this with e.g. `app('basset.output')->stylesheets('print')` because Basset will produce generic <link/> html code.

I'd like to have a possibility to declare somehow different HTML code for embedding my assets (something like `app('basset.output')->stylesheets('print', '<link href="%s" media="print" rel="stylesheet" type="text/css" />')`).

What do you think about it?

**Comment by jasonlewis** [comment]
This is similar to #111, correct? I'm going to seriously consider this now. Could you please read over the discussion there and let me know what you think.

The only problem with this is when you build your collection into a single file (or two files if you have CSS and JS) then what attributes are applied? Do you apply attributes to the collection as a whole, perhaps separate them onto CSS and JS (so you can add diufferent attributes to the generated CSS HTML).

I like the approach you've shown, specifying the format you'd like.

**Comment by radmen** [comment]
> This is similar to #111, correct?

Yes.

> The only problem with this is when you build your collection into a single file (or two files if you have CSS and JS) then what attributes are applied?

That's why I think that these attributes should not be defined in config file. 
I'll use very short example for this:
- for page `/article/1` I want to to embed my `application` collection and `print` with `media="print"`
- for page `/print/1` (same as `/article/1`, but it's "print preview") I want to embed `application` and `print` collections  normally.

If attributes would be set for collection I'd have to define two collections for `print` just to generate a little bit different HTML output.

Let the developers decide if they're ok with default HTML. If not they can change it in view. 
For most cases this solution should be ok.

**Comment by jasonlewis** [comment]
Yes that makes sense. I'll implement this much like how you've done it. I'm awaiting a couple of merges to Laravel itself before I can push some changes though.

**Comment by radmen** [comment]
Cool, thanks!

**Comment by jasonlewis** [comment]
No worries. You have to supply an array to one of the methods, with the key being the collection identifier and the value being the desired format. [See examples on the docs](http://jasonlewis.me/code/basset/4.0/views#custom-formats).
