### ISSUE TITLE
Dynamic script injection

### ISSUE THREAD

**Issue by KaneCohen** [jasonlewis/basset#129]
Just reporting something i've noticed while using TinyMCE with Basset.

TinyMCE, as some other large JS apps, use dynamic script injection to add extra modules after page load. TinyMCE does that by picking path to the tiny_mce.js file (with Basset it might look something like that: example.com/fs2352hd4352B/application/vendor/tinymce/tiny_mce.js). And then replacing last part of the path with path to each module that is being loaded. But, since those scripts are not included in the current collection, they won't load leading to number of errors and basically disabled TinyMCE.

I'm not exactly sure how to handle this situation with Basset (i doubt full compilation to one file is desirable), but in case of TinyMCE i can advice putting whole thing in you public folder assets and changing base TinyMCE path to that directory (script_url in jquery version of tinymce).

Maybe there's a simple way around, but i haven't explored Basset to the full extend yet.

**Comment by jasonlewis** [comment]
I'll have a look at TinyMCE specifically. But in the changes I'm going to push some time soon assets are built automatically when changes are detected on a page load. Built assets will also have a fingerprint injected into their filenames. So instead of having the example you posted above you might have something like `localhost/builds/application/vendor/tinymce/tiny_mce.js`. Would that still result in TinyMCE not being able to load correctly?

**Comment by KaneCohen** [comment]
@jasonlewis, in this case, let's say tinyMCE is loading English language file from: `tinymce/themes/advanced/langs/en.js`. With example above, it'll look for lang file in `localhost/builds/application/vendor/tinymce/themes/advanced/langs/en.js`. I guess if we add whole directory to the build it'll be there (but only if directory structure is left unchanged).

Maybe add a flag to directory(), `keepStructure()` which will tell Basset that it has to keep whole directory and inner directories intact while creating a build. With this flag whole directory could be just copied to the correct place in public folder.

**Comment by jasonlewis** [comment]
Structure is already maintained for development builds. But I could see this being a problem if you try to build the collection for production (combining into the one file).

**Comment by KaneCohen** [comment]
@jasonlewis, yep, i was talking about compilation into one file.

> Built assets will also have a fingerprint injected into their filenames.

Depends on where you're injecting fingerprints. Consider `tinymce/themes/advanced/langs/en.js`. If fingerprint is added like `125stgdsw325-en.js` then tinymce won't be able to use it because it doesn't know anything about fingerprints. But if fingerprint is injected after `?` like `en.js?125stgdsw325` then it'll be fine.

**Comment by jasonlewis** [comment]
Tiny MCE seems fiddly. :unamused: Haha.

The fingerprint is injected after, but not as a query string. So it's like `en-1239sds0vss8324.js`.

**Comment by KaneCohen** [comment]
@jasonlewis, indeed. TinyMCE is quite something. But, i imagine, other large JS apps might work in a similar fashion.

**Comment by jasonlewis** [comment]
I'm not sure what I can do here though. The point of serving a production collection is to build it into a single file. Of course, if you wanted to, you don't have to build the collection for production.

**Comment by KaneCohen** [comment]
@jasonlewis, as i said before, only way i see is to make some directories protected from compilation and just copy them during "build" into the public assets folder (or whenever scripts/css/imgs are stored).

**Comment by jasonlewis** [comment]
I'm not sure if this is going to be of any use to you but you can exclude assets from the build.

I've just added the ability to set an entire directory to use raw paths.

```
$collection->requireDirectory('assets/tinymce')->raw();
```

Or you can do that on an individual asset.

```
$collection->add('tinymce.js')->raw();
```

**Comment by KaneCohen** [comment]
Nice. Thanks!
