### ISSUE TITLE
Google maps api not recognized as javascript

### ISSUE THREAD

**Issue by dipsynl** [jasonlewis/basset#130]
The google maps api is not recognized as a javascript file.

$collection->add(https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true);

**Comment by jasonlewis** [comment]
I'm going to improve the type detection, hopefully this will get around these issues.

**Comment by Anahkiasen** [comment]
I don't really think there's any way to detect these kind of cases – same thing for Google webfonts : no `.css` in the URL.

**Comment by dipsynl** [comment]
Maybe you can assign the type with a extra argument.

Like:

$collection->add(https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true, 'js');

or

$collection->addJavascript(https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true);

**Comment by Anahkiasen** [comment]
I'd prefer `addScript` or `addStylesheet` yeah, we may need arguments for something else later, I wouldn't want having to specify the type of the file to use a potential third argument.

**Comment by jasonlewis** [comment]
Yeah can work it in like that. Would opt for `$collection->stylesheet()` and `$collection->javascript()` methods. Sound good?

**Comment by dipsynl** [comment]
Sounds good to me!!

**Comment by jasonlewis** [comment]
You can now add assets with `stylesheet` and `javascript` methods. I've also implemented better type detection if the extension is not one of the possible extensions by using cURL to check the content type. Of course, it's much better to just explicitly define the type with one of the mentioned methods.
