### ISSUE TITLE
Missing compliler 4.0.0 Beta 1

### ISSUE THREAD

**Issue by dipsynl** [jasonlewis/basset#133]
After the last update i get the following error:
Missing argument 2 for Basset{closure}()
open: 
<c
vendor/jasonlewis/basset/src/Basset/BassetServiceProvider.php
     * 
     * @return void
     */
    protected function registerBladeExtensions()
    {
        $blade = $this->app['view']->getEngineResolver()->resolve('blade')->getCompiler();

```
    $blade->extend(function($value, $compiler)
    {
        $matcher = $compiler->createMatcher('javascripts');
```

**Comment by jasonlewis** [comment]
Ah, my bad. I submitted a pull for this on the framework and forgot to switch it back since the compiler isn't actually given as a parameter. I'll push a fix in a sec.

**Comment by jasonlewis** [comment]
Should be fixed. Try updating again.

**Comment by dipsynl** [comment]
It's working after the update. Thnx

**Comment by jasonlewis** [comment]
No worries. Silly mistake. :smile:
