### ISSUE TITLE
Basset\Directory::except() weird behavior 

### ISSUE THREAD

**Issue by radmen** [jasonlewis/basset#136]
This issue is related to #135 (same problem - assets order).
I want to except some files from directory.

The problem is that Basset\Directory::except() uses `$asset->getRelativePath()` which returns something like `e31152dd219c9fa6464cead6c9e85150/bootstrap-lightbox.js`.

In that situation I can't exclude some files using e.g.

``` php
$collection->directory('../app/assets/javascripts', function($c) {
  $c->requireDirectory()->except(['../app/assets/javascripts/jquery.js']);
});
```

**Comment by jasonlewis** [comment]
My advice is to move assets into your public directory. I know people want to store them outside public. But it causes more problems then just this. Some filters throw their arms up with the weird paths, etc.

**Comment by radmen** [comment]
k I can try it, but does it make sense since the default Basset config points to `../app/assets` directory?

**Comment by jasonlewis** [comment]
The default application collection no longer points to `../app/assets` but instead to `assets`.

**Comment by radmen** [comment]
oh, didn't notice that. Thanks I'll try it later.

**Comment by radmen** [comment]
Moving assets to public fixed the problem.

**Comment by karlaredor** [comment]
Hi, I'm experiencing a problem wherein the other scripts are included even if I exclude the script. I also tried using only but it still keeps on loading the other scripts that I don't want to include. Hope you can help me on this one. Thanks in advance.
