### ISSUE TITLE
Conditional JS/CSS

### ISSUE THREAD

**Issue by syphernl** [jasonlewis/basset#139]
It would be nice if conditional JS/CSS could be used like:

```
<!--[if lt IE 9]><script src="{{ URL::asset('js/html5shiv.js' ) }}" type="text/javascript"></script> <![endif]-->
```

**Comment by jasonlewis** [comment]
You can already do this, however it will be applied to all assets in a collection. See [custom formats](http://jasonlewis.me/code/basset/4.0/views#custom-formats) on the docs. If that's not going to help then just load that script manually.
