### ISSUE TITLE
Internal server error on loading assets with dash in name

### ISSUE THREAD

**Issue by radmen** [jasonlewis/basset#141]
I've tried to install [jhollingworth/bootstrap-wysihtml5](https://github.com/jhollingworth/bootstrap-wysihtml5).
It's files have dash in name (e.g. `bootstrap-wysihtml5-0.0.2.js`).

In devel env I've got 500 error. The file is not copied to `builds` directory.

It happens only when in asset name is dash. After replacing with dot assets loaded normally.

**Comment by jasonlewis** [comment]
I've just tried a simple file with dashes and it's working fine for me.

Will try the mentioned package myself and see if I can reproduce.

**Comment by radmen** [comment]
You've added it with `$collection->add()`? I forgot to mention that the file was included in collection with `requireDirectory()`.

**Comment by jasonlewis** [comment]
Yep this was done with a `requireDirectory` as well. I'll try some other variations (also pulling in some L4 updates). Can you check your server logs in the mean time as to why you're getting an internal server error.

**Comment by radmen** [comment]
> Can you check your server logs in the mean time as to why you're getting an internal server error.

I guess I don't have to.

Correct me if I'm wrong, but Basset on dev env copies assets to build dir and links to them, right?
It's a public dir, so links to this assets  are not going through Laravel.

In my case the file was not copied to build dir, and link to it goes through Laravel routing.

Today I've checked other app on other machine, and there's no problem with dashes in files names.

I guess that this issue needs to be closed. I'll try to investigate it on my own.
