### ISSUE TITLE
Log warning if you're relying on external HTTP fetch to find out the type of asset

### ISSUE THREAD

**Issue by julien-c** [jasonlewis/basset#149]
I'd suggest logging a warning if you're relying on external HTTP fetch to find out the type of asset, because this can really slow things down a lot (especially as in the current implementation you might end up fetching the file multiple times on the same request).

Should I go ahead and PR?

Cheers!

**Comment by jasonlewis** [comment]
I'm going to tweak the logging and allow it to be disabled. I'll throw this in too. Thanks.
