### ISSUE TITLE
[Request] Define the path to assets other than relative to the public directory

### ISSUE THREAD

**Issue by marvinschroeder** [jasonlewis/basset#153]
Would be great to define a path to the assets other than relative to the public directory.

For example to a directory beneath "app" (/app/assets/) or something other path.

> Config::('basset.asset_path', '/srv/www/some/path/');

**Comment by jasonlewis** [comment]
You can already, although I'm not encouraging it.

```
$collection->directory('../app/assets', function($collection)
{
    // Now in app/assets
});
```

It's a lot less trouble if everything is in public. Some things won't work outside public. Like rewriting relative URIs.
