### ISSUE TITLE
Allow versioning of assets

### ISSUE THREAD

**Issue by kloy** [jasonlewis/basset#16]
In order for cache busting to work effectively, css and js files need a version number in the file name. If would be nice if this were supported within basset instead of having to add version numbers to names when creating containers. 

A solution I think is elegant is adding a config option for "version" which accepts the follow parameters...

false (No versioning)
true (auto versioning where every file change bumps version numbers by one)
string (named file version to allow explicit version numbers)

To take this even further a method could be added to Asset, maybe Asset::version(). This would allow versioning on a per group basis.

To prevent confusing URL::to statements implementing https://github.com/jasonlewis/basset/issues/15 in conjunction with this feature would possibly be ideal.

**Comment by jasonlewis** [comment]
Just thinking about this now. I think it'll be possible by doing it with the `filemtime()` of each asset, or using something similar. I'll work on this for Basset 2 as well.

**Comment by kloy** [comment]
filemtime() can be finicky with static assets across multiple servers (like a CDN) so you have to be careful. You may want to prefix the version with some type of server identifier to prevent the same assets from being versioned. The simple fix of course is to allow people to set the version using a string.

**Comment by jasonlewis** [comment]
Yeah it depends I guess. I use caching on a staging server and basically when I deploy an updated development version it performs some operations such as deleting any cached files that I have stored in several directories. It's not like you use caching when developing.

**Comment by jasonlewis** [comment]
I'm going to leave this open for now in case others or yourself have more to say on this issue.

**Comment by barryvdh** [comment]
An option for versioning would be nice.
A simple timestamp should work for local files (style.css?12324234), but it would be better to have style.12324234.css, that shows style.css (doesn't have to be timestamp, could also be version).
(See h5bp docs on cache busting; https://github.com/h5bp/html5-boilerplate/blob/v4.0.1/doc/htaccess.md)

This way users will automatically get a new version, instead of the (client-side) cached version.

**Comment by Anahkiasen** [comment]
+1 for a cache-buster option in Basset.
