### ISSUE TITLE
Default config errors

### ISSUE THREAD

**Issue by barryvdh** [jasonlewis/basset#160]
When you use the default config file, you get a lot of errors (in the profiler/logger). Shouldn't you make the configuration so that it always works by default? Also, why are those checks done, when I don't use the application filter?

`Directory "less" could not be found in ..`
`Failed to find required constructor argument for filter "Sass\ScssFilter".`
etc.

**Comment by jasonlewis** [comment]
Yeah this is a problem. This is only happening because of the recent split. I think I might have to go back to everything being in the one configuration file. That way when you override the collections the application collection is removed as well.

**Comment by jasonlewis** [comment]
The config file split has been reverted. Overwriting the collections key should remove the application collection and will hide these errors.

**Comment by barryvdh** [comment]
Okay but you would still have to publish the config file? I usually don't use the config, but just add the the collections using Basset::collection()

**Comment by jasonlewis** [comment]
Yeah you would still need to publish the config and remove the collection. Not much else I could do in that regard I don't think.
