### ISSUE TITLE
Create a develop branch

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#161]
Hi, we're using Basset 4 and it kind of keeps breaking, kind of regularly actually. I think it would be best if you were to create a **master** and a **develop** branch so that we could use Basset 4 without the API changes or bugs that happen on occasion.

**Comment by arthurdarcet** [comment]
:+1: please

**Comment by jasonlewis** [comment]
It's still in beta. Just be aware of it.

I'm trying not to push too many breaking changes.

**Comment by julien-c** [comment]
:+1: :ambulance:

**Comment by jasonlewis** [comment]
There will probably be a few more changes happening soon that might break. I'm probably going to revert back to the original configuration setup. This will fix #160.

Please, bare with it. :smile:

**Comment by ivannpaz** [comment]
+1 to a development branch we can checkout if we want to play/help with it if you don´t mind.
