### ISSUE TITLE
Clean Up Directory and File Names

### ISSUE THREAD

**Issue by ghost** [jasonlewis/basset#163]
Could we append the string as  `?v=RANDOMSTRING` instead of the actually changing the filename and/or directory structure. I think we could pull the string from the manifest. Appending seems (I do not have numbers to support my arguement) to be the standard, and feels much cleaner to me.

We could probably add the string as a comment as the first line of the generated files as well to ensure that the files generated are the ones we wanted.

I am using the composer packages of both Twitter Bootstrap and Zurb Foundation and these URL's are a pain in the arse.

**Comment by jasonlewis** [comment]
I think appending only seems to be the standard because it's so damn easy. Appending the fingerprint as a query string isn't the best way of going about it. Rails itself has [moved away from query strings](http://edgeguides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark). While the article [most people link to](http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/) is rather old I still think injecting the fingerprint as part of the file name is a much safer way of going about it.

Why are the URLs a pain in the arse?

And again I see people are using asset oriented packages through a PHP PACKAGE MANAGER. :confused:

**Comment by jallits** [comment]
I agree, but all we really have is Component, which I really do not trust at this point. Do you have a favored alternative?

**Comment by jasonlewis** [comment]
No, I don't. I'm actually tinkering with the idea of a `basset:publish` command that will allow you to publish the assets of a collection to your `public` directory (where they actually belong).

**Comment by jallits** [comment]
How are you envisioning that working?

**Comment by jasonlewis** [comment]
Still tinkering.

At the moment I'm thinking you might need to actually do it from within a collection. Something like:

```
$collection->publish('path/to/directory');
```

Or, for example, if you're within a directory.

```
$collection->directory('../vendor/twitter/bootstrap', function($collection)
{
    $collection->publish('img', 'js', 'less');
});
```

Then, my thoughts are that you still reference the old location of the assets, but internally Basset will check to see if a published copy exists.

Got any ideas?

**Comment by jallits** [comment]
Looks like you are supporting fonts and images as well? +1 to that!

By the way I read the linked material regarding query strings and I am convinced you went down the right path. I concede my request.

**Comment by jasonlewis** [comment]
Yeah it should allow the publishing of everything. If this all works out.

No worries. I'll close this for now. Thanks @jallits.

**Comment by jallits** [comment]
Real quick. I believe assets should be namespaced as well in the`public` directory.

**Comment by jasonlewis** [comment]
Could you expand on that?

**Comment by jallits** [comment]
If I used twitter bootstrap as a collection the directory structure would resemble `/public/builds/twitter/bootstrap/*`. Or if Zurb Foundation was used the structure would be `/public/builds/zurb/foundation/*`.

Custom assets would have to be defined in the collection.

NOTE: Examples use the default `/public/builds` structure.

**Comment by jasonlewis** [comment]
Is this in reference to the published assets of each? I'm not sure how the structure will look at the moment. The less replacing of directories the better, if that makes sense. I know it'd be nice if it just grabbed the `vendor/package` directory and just used that. But that's not reliable. Especially if the assets aren't in the vendor directory.

They'll most likely be published to the builds directory though.

**Comment by jallits** [comment]
I mean in our collection we would define our asset directories outside of the `public` directory. Only those defined assets (twitter/bootstrap/less, twitter/bootstrap/js, twitter/bootstrap/img) would be published to the `public` directory keeping the vendor/package namespace. Your [droplr screenshot](http://d.pr/i/EYnD)  accurately does as I was asking and what I would have expected.

There is no reason to publish the additional content like docs, Ruby/Gen Pacakage info, and license.txt files.

**Comment by jasonlewis** [comment]
No, of course not. It will only publish what you tell it to. :smile:

**Comment by drbroad** [comment]
Not to beat a dead horse - but appending the string as opposed to baking it into the filename, will also help the live reload issue where the browser tries to reload the old collection filename. At least if its a string and it reloads the collection it will serve the new files contents (scripts and stylesheets)
