### ISSUE TITLE
EmberPrecompileFilter

### ISSUE THREAD

**Issue by realsurfer** [jasonlewis/basset#167]
Hi,

I am using the latest basset and trying to get EmberPrecompileFilter to work. I have looked at the construct arguments in the Assetic file and in the basset config I use setArguments to match what is required yet nothing happens. I don't get any errors at all.
Even if I misspell the arguments or filtername I don't get an error. I have tried compiling the files manually via the command line and that works.

My config file looks like:

```
'EmberPrecompile' => array('EmberPrecompileFilter', function($filter)
            {
                $filter->setArguments('/var/www/node_modules/ember-precompile/bin/ember-precompile', '/usr/bin/node');
            }),
```

and 

```
$directory = $collection->directory('js', function($collection)
            {
                //$collection->requireDirectory('coffeescripts')->apply('CoffeeScript');
                //$collection->requireDirectory('vendor');
                $collection->javascript('vendor/jquery.min.js')->raw();
                $collection->javascript('vendor/handlebars.js')->raw();
                $collection->javascript('vendor/ember.js')->raw();
                $collection->javascript('vendor/ember-data.js')->raw();
                $collection->requireDirectory('vendor/bootstrap');
                $collection->requireDirectory('templates')->apply('EmberPrecompile');
                $collection->requireDirectory();
            });

            $directory->apply('JsMin');
```

Appreciate any help!
Thanks

**Comment by realsurfer** [comment]
After some debugging I think I found the problem. As the handlebar templates have the extension .hbs basset ignores these files. When I rename them to .js the files are compiled. The problem is that they need to have the .hbs extension in order for the ember-precompiler to do it's magic correctly.

How do I solve this?

**Comment by realsurfer** [comment]
When I added .hbs to the javascript extensions in Asset.php it works.

```
protected $allowedExtensions = array(
        'stylesheets' => array('css', 'sass', 'scss', 'less', 'styl', 'roo', 'gss'),
        'javascripts' => array('js', 'coffee', 'dart', 'ts', 'hbs')
    );
```

**Comment by jasonlewis** [comment]
Ah was wondering if I had missed any extensions. Will at that in.

**Comment by realsurfer** [comment]
FYI, I think handlebars templates also use the ".handlebars" extension but I might be wrong.
See https://github.com/gabrielgrant/node-ember-precompile which is the lib the ember filter uses.
