### ISSUE TITLE
basset:publish Error on Development Branch

### ISSUE THREAD

**Issue by ghost** [jasonlewis/basset#168]
`php artisan basset:publish foundation`

{"error":{"type":"ErrorException","message":"preg_replace(): Unknown modifier 'r'","file":"\/vendor\/jasonlewis\/basset\/src\/Basset\/Factory\/AssetFactory.php","line":112}}

I believe this is caused because forward-slashes are being used as your regex pattern delimeter. Swapping out for another character such as the tilde (as shown below) should work.

``` php
$path = preg_replace('/^'.preg_quote($this->publicPath).'/', '', $path);
```

replace with 

``` php
$path = preg_replace('~^'.preg_quote($this->publicPath).'~', '', $path);
```

**Comment by jasonlewis** [comment]
Ah good pick up. I'll add the slash as the second parameter to preg_quote

**Comment by jasonlewis** [comment]
Pushed a possible fix for this.

**Comment by jallits** [comment]
Looks good to me.
