### ISSUE TITLE
Second collection doesnt work

### ISSUE THREAD

**Issue by subdesign** [jasonlewis/basset#169]
If I add a second collection to the config file, next to 'application', and fire the command

_php artisan basset:build secondasset_

I get the message: [secondasset] Collection not found.

I guess because the array name is Collections, I can add more than one.

(also run --delete-manifest command, then rerun the build command, same..)

thx

Edit:

'backendassets' => function($collection)
        {
            $directory = $collection->directory('assets/stylesheets', function($collection)
            {
                $collection->stylesheet('bootstrap.css')->apply('CssMin');
...

Error in log file: [2013-06-13 20:57:41] basset.ERROR: Asset "stylesheets/bootstrap.css" could not be found in "/var/www/xyz/public" [] []

If I set the assets folder in the $directory variable, why Basset cant found the asset?

**Comment by jasonlewis** [comment]
I'm not sure why it's not working on your end. I'm able to have multiple collections in the config and it builds them correctly.

I have a feeling you have some old code. Check your composer.json and make sure the version for Basset is dev-master, just for the time being. Then run composer update. You might be running on an older beta tag.

**Comment by subdesign** [comment]
Yes, updated Basset today, and now everything works. Thanks
