### ISSUE TITLE
Class 'Basset\BassetServiceProvider' not found

### ISSUE THREAD

**Issue by ranaanees** [jasonlewis/basset#171]
Hii,

I deployed Basset for Laravel 4 package on my shared hosting server....

I upload following files...
1. vendor->jasonlewis 
2. assets and builds folders
3. app.php in config
4. app->config->packages-> jsonlewis folder

Receiving following exception...

Symfony \ Component \ Debug \ Exception \ FatalErrorException
Class 'Basset\BassetServiceProvider' not found
open: \FSC02-S03\WWWROOT$\maskany.com.sa\wwwroot\bootstrap\compiled.php
                $manifest['eager'][] = $provider;
            }
        }
        return $this->writeManifest($manifest);
    }
    public function createProvider(Application $app, $provider)
    {
        return new $provider($app);
    }
    public function shouldRecompile($manifest, $providers)

**Comment by jasonlewis** [comment]
You'll need to update your composer autoloader as well. Run `composer update` or you could try uploading the fresh `vendor/autoload.php` file.

**Comment by ranaanees** [comment]
I found solution...Along with Package specific directories....also upload 

1) vendor/autoload.php
2) vendor/composer folder
