### ISSUE TITLE
Deprecated docs on Aliased Assets

### ISSUE THREAD

**Issue by seppestas** [jasonlewis/basset#178]
In the docs of Basset it says under Aliased Assets:
"When an asset is added it's name is first checked against the existing aliases in the configuration. You might like to alias assets that are used in multiple collections. Aliased assets go in the aliases.php configuration file." 

However, there isn't any aliases.php file as far as I can see. The array containing the aliases is in the config.php file. This is probably because the docs are deprecated. Could they be updated?

Edit: imo it would also be worth mentioning the 'php artisan basset:build' command needed to get to that config file in this section...

**Comment by jasonlewis** [comment]
Yeah will update it eventually. Sorry, I'm rather busy at the moment so everything has kind of come to a stand still. Also, the config file should be published with `php artisan config:publish jasonlewis/basset` and I believe that is mentioned in the docs.
