### ISSUE TITLE
Laravel Blade Integration

### ISSUE THREAD

**Issue by GrahamCampbell** [jasonlewis/basset#188]
Whenever i use your blade syntax for serving css, @stylesheets, the html generated has a semi-colon on the end.

**Comment by eviweb** [comment]
Hi,

it seems the blade engine does not considered semi-colons after a blade command as part of the command.
use @stylesheets() instead of @stylesheets(); should do the trick

Eric

**Comment by GrahamCampbell** [comment]
That's what I was using, but it didn't always work. Sorry I can't remember the exact scenarios anymore.
