### ISSUE TITLE
Driver architecture for assets

### ISSUE THREAD

**Issue by kloy** [jasonlewis/basset#19]
Use Case: Needing to add a javascript template asset handler or wanting to handle css files differently without modifying BAsset.

It would be nice if assets where handled in a driver fashion. This would allow custom assets to be added into the BAsset pipeline without modifying the bundle.

**Comment by jasonlewis** [comment]
Yeah could be done. I've got some other plans for it to. You're a legend
Keith.
On Jun 7, 2012 12:27 PM, "Keith Loy" <
reply@reply.github.com>
wrote:

**Comment by jasonlewis** [comment]
What sort of work do you want to perform on assets? I was thinking of injecting some events into the process.

Let's say we have an event fired for each asset, such as **basset: <route>.<asset>** for each asset, this could be fired before an asset is compressed or anything is done to the asset. There could also be a **basset.done** event that's fired after all assets have been compressed and compiled where you can make further refinements or whatever to the assets.

Does that sound alright?

**Comment by kloy** [comment]
That could work. I was more thinking of a register() method were you would register an asset handler for an extension and pass the group (style or script) that it belongs to.

**Comment by jasonlewis** [comment]
Damn, GitHub didn't post it properly.

```
basset: <route>.<asset>
```

That's what I had above. So say the route is **website** and the asset name is **jquery**.

```
Event::listen('basset: website.jquery', function(){});
```

So when you say you register a handler for an extension you mean either scripts or styles, correct?

**Comment by kloy** [comment]
Registering a handler for an extension would be more like...

`Basset::register('tmpl' /* extension */, 'scripts' /* group */, function() {} /* callback */);`

The callback would allow you to handle the parsing of the asset to get to a standard asset format supported by the browser, js or css. From there the asset can be treated like any other js or css file in Basset.

**Comment by jasonlewis** [comment]
Can you give a better example of how you would use it. Still not fully getting how you'd like to see this implemented. Cheers.

Edit: At the moment I'm still thinking of implementing events to be fired at certain stages of Bassets operation.

**Comment by jasonlewis** [comment]
@kloy If you can are you able to get back to me on this? Going to push Basset 2 soon, and at the moment have implemented the event firing that I mentioned on the develop branch.

**Comment by kloy** [comment]
@jasonlewis sorry I have been away. Events can accomplish the same requirement which is to allow more flexible parsing of assets.

**Comment by jasonlewis** [comment]
All good mate! Yeah so at the moment all that is passed to the listener is the file contents before any compression or minification is performed so you can do whatever you want to it, sound good?

**Comment by kloy** [comment]
I just looked at the code real quick. That should work as compression and minification is expected to happen on js and/or css.

**Comment by jasonlewis** [comment]
Yep all good. This is now in the develop branch then. Should be merged to the master very soon. Thanks @kloy!
