### ISSUE TITLE
Route Based Loading simply don't work

### ISSUE THREAD

**Issue by Meroje** [jasonlewis/basset#2]
I don't see anything in the logs, my server (MAMP) is simply returning me a 500.
Here is how I use Basset, it's my first time with it

```
'GET /basset/template.css' => function()
    {
        return Basset::add('reset', 'reset.css')
            ->add('common', 'common.css')
            ->add('form', 'form.css')
            ->add('standard', 'standard')
            ->add('fluid-960', '960.gs.fluid.css')
            ->add('simple-lists', 'simple-lists.css')
            ->add('block-lists', 'block-lists.css')
            ->add('planning', 'planning.css')
            ->add('table', 'table.css')
            ->add('calendar', 'calendar.css')
            ->add('wizard', 'wizard.css')
            ->add('gallery', 'gallery.css');
    },
```

``` php
    <?php echo HTML::style('/basset/template.css'); ?>
```

Do I did it wrong ?

**Comment by jasonlewis** [comment]
You get a 500 error when trying to load the route /basset/template.css? Have you defined the correct paths in the config/basset.php file?

Basset will be changing quite a bit come Laravel 2.0 as well. Depending on where things go with 2.0, so just a heads up.

**Comment by Meroje** [comment]
I'm using default paths (/public/js and /public/css), do I need to set something ?

EDIT: I uploaded on my ftp and i also get a 500, but i also have this in my logs : 

`[28-Oct-2011 20:09:47] PHP Fatal error:  Method Basset\Basset_Container::__toString() must not throw an exception in public_html/laravel/system/laravel.php on line 180`

EDIT2: So now I get this after commenting the line 314 in modules/basset/libs/basset.php :

`file_get_contents(/css/reset.css) [function.file-get-contents]: failed to open stream: No such file or directory in SYS_PATH/file.php on line 13.`

EDIT3: I'm wondering why do the $this->assets have the script array in it : 

```
[script] => Array
(
            [standard] => Array
                (
                    [file] => standard
                    [path] => default
                    [dependencies] => Array
                        (
                        )

                    [less] => 
                    [type] => script
                )

)
```

**Comment by jasonlewis** [comment]
I'll take a look at this tonight. Get back to you shortly.

**Comment by Meroje** [comment]
I'm so confused, after a lot of debugging on you class, i finally noticed that I forget the css extension for the standard.css file. I verified my file list many times but didnt saw that. I think you should do a better check in the add function and throw an exception there.
So now I have the file_get_contents problem.
Do you have an idea on how to fix that ?

**Comment by jasonlewis** [comment]
What's your directory structure look like? Did you upload your 'public' contents into the 'public_html' and the rest is below that directory? Or did you upload it all into public_html and access it via www.yourwebsite.com/public/

If the latter is the case you'll need to change the default in the config to be 'public' or something similar.

**Comment by Meroje** [comment]
I fixed it this way :

``` php
    /**
     * get_asset
     *
     * Fetches an asset file.
     *
     * @param  array $asset Array of asset data.
     * @return string
     */
    public function get_asset($asset)
    {
        if(!parse_url($asset['file'], PHP_URL_SCHEME))
        {
            // If it's not a well-formed URL than it's part of the local directory.
            $path = ($this->get_path($asset['path']) === "/") ? "" : $this->get_path($asset['path']);
            $asset['file'] = $path . $this->folders[$asset['less'] ? 'less' : $asset['type']] . '/' . $asset['file'];
        }

        $call = array('\System\\File', 'get');
        $params = array($asset['file']);

        if(!$this->settings['routed'] && !$this->settings['inline'])
        {
            $call = array('\System\\HTML', $asset['type']);

            if($asset['less'])
            {
                $params[] = array('rel' => 'stylesheet/less');
            }
        }

        return call_user_func_array($call, $params);
    }
```

**Comment by jasonlewis** [comment]
I'll take a look at your fix. I must have missed something with the default directories since I never used them. Thanks for this. I appreciate it. Good to see more people using Laravel too.

**Comment by Meroje** [comment]
I missed your previous comment.
To answer, Im using a subdomain pointing to the public directory of laravel both on the ftp and locally.

EDIT: please note that my fix is only a hack to get rid of the slash in front of the path when using default directory, I think that something like realpath() would be better.

**Comment by jasonlewis** [comment]
I'm going to close this as it's no longer being supported for Laravel 1.x. I'll get a bundle out for Laravel 3 shortly.
