### ISSUE TITLE
Add to existing asset routes

### ISSUE THREAD

**Issue by wildlyinaccurate** [jasonlewis/basset#21]
Is it possible to add to an existing route? For example in my routes.php file I do

```
Basset::scripts('default', function($basset)
{
    $basset->add('jquery', 'public/assets/js/jquery-1.7.2.min.js');
    $basset->add('css3-mediaqueries', 'public/assets/js/css3-mediaqueries.js');
});
```

But then in a controller I would like to include some extra assets to that same route, i.e.

```
Basset::scripts('default', function($basset)
{
    $basset->add('some-script', 'public/assets/js/some-script.js');
});
```

So basset/default.js would now contain jquery, css3-mediaqueries, and some-script. This doesn't seem to work at the moment; some-script isn't included in the compiled asset.

**Comment by jasonlewis** [comment]
I don't think that would be possible with the current implementation but I
can certainly look at it for you. :)
On Jun 9, 2012 11:18 PM, "Joseph Wynn" <
reply@reply.github.com>
wrote:

**Comment by wildlyinaccurate** [comment]
That'd be great, thanks. I'll have a look at implementing it as well and submit a pull request if I get anywhere with it.

**Comment by jasonlewis** [comment]
I'm going to be doing a big overhaul for Basset 2, I'll try to implement something so this can be achieved. I have some pretty neat ideas.

**Comment by wildlyinaccurate** [comment]
Awesome! I haven't started looking into this yet but it sounds like you've got it sorted so I'll hang around for Basset 2. Thanks Jason.

**Comment by wildlyinaccurate** [comment]
Hi Jason, I was thinking about this feature over the weekend. What I failed to realise when I reported this issue is that browsers will be caching assets.

If you look at my original example, imagine that the first page load only contains jQuery and css3-mediaqueries. The browser will download and cache this. On the next page load the browser will just grab its cached version, even though we might have added more scripts to the asset.

I don't think I had really considered the consequences of this feature before I reported this issue. What do you think?

**Comment by jasonlewis** [comment]
I can prevent the browser from caching the assets though, and leave it up to the developer to leverage the caching built in when they need it. Using the header I can turn off caching and I can adjust the Basset::show() method to append a unique string on each page load.

I didn't encounter any problems in my testing after implementing this solution. It actually works quite well but you have to generate the assets from a non-Basset URL. So if you have assets being generated at `basset/website.css` and you visit that URL the assets won't be generated correctly. You need to generate them through your normal website.

If you can do you mind pulling down the develop branch and testing it on your application? I have a couple other things in mind before I tag Basset 2 possibly later today/tonight.

Here is a paste explaining some things: http://paste.laravel.com/1SE
