### ISSUE TITLE
Production versions sometimes go stale?

### ISSUE THREAD

**Issue by dustingraham** [jasonlewis/basset#217]
Step 1: How to further diagnose this problem?

Step 2: Determine if it's my problem, or possibly a more general problem with building for production.

I'm having a strange situation occur. I have everything working pretty nicely. Less compiles, css concatenation, jsmin, etc.

I go to do a build `php artisan basset:build --production` and it compiles the production build files. I reload my production page and it shows just two includes (I have two main collections) like it should. Then randomly, at some later point, it decides to revert to serving the un-compressed files. It still serves them from the /build/ folder with the filename-hash suffix. It just isn't using the compiled compressed builds.

I'm wondering if this is something on my server messing with timestamps. Sometimes it's a few minutes, sometimes it's an hour or more, but it always seems to revert. What I'm wondering is, how can I further diagnose this? It doesn't happen locally, so I need to enable some logging or analysis on my production box.

I'm wondering about how it determines that the files are stale. It looks like it keeps a fingerprint record in meta/collections.json

Mine looks something like this

```
{
    "application": {
        "fingerprints": {
            "stylesheets": "application-84edb4b0d213f60c10e600acb627a9ee.css",
            "javascripts": "application-9de712a6fc162e1f42aee87094f0e155.js"
        },
        "development": {
            "stylesheets": {
                "..."
            },
            "javascripts": {
                "..."
            }
        }
    },
    "reseller": {
        ...
```

Any thoughts?

**Comment by dustingraham** [comment]
Another note, when it does go stale, application.fingerprints does revert to just `"fingerprints": [],`

Makes me wonder if there's a specific page on my site which is doing something to reset the fingerprints... Trying to see if I can force it to happen by visiting some page.

**Comment by dustingraham** [comment]
Should it be writing to collections.json _every_ page load? 

**Update:** Ah, the reason it's writing my collections.json every time is because I have a "dummy" collection called _other_ which I use to hold files that are added dynamically depending on the page.

This isn't the direct cause of this stale issue, but it might give me a hint... writing every page load could be problematic with the level of traffic.

**Comment by dustingraham** [comment]
Reworked my collections so I no longer have an "other" that is dynamically built. However, on my production server even though I run `php artisan basset:build --env=production` then `cat app/storage/meta/collections.json` fingerprints is empty `[]` ... not sure why.

**Edit:** Okay, one problem was that `--env=production` isn't used for this command... `--production` is the flag to compile for production.

**Update:** After adding some debug statements that indicated which step was causing development builds to be used, and isolating the missing fingerprint, then using the proper flag `--production` and adjusting some permissions (command line vs apache) I've gotten production pulling proper build files again.

Now we wait to see if removing the "other" dynamically built sheet was the culprit that caused the builds to go stale or not.

**Comment by fedeisas** [comment]
@dustingraham I'm having issues with collections.json as well. Sometimes the fingerprint for `collections.json` is different to the fingerprint from the actual file in `/builds`.

My guess is that if you get a request in the middle of the building process, it breaks.

**Comment by dustingraham** [comment]
Things have been relatively stable over the past few days since I migrated away from a "custom" module. What I was doing was creating a `Basset::collection('other')` from my controllers that I was adding to as needed. This caused `collections.json` to be re-created on _every_ page load. It caused quite a bit of overhead, and as you pointed out it probably meant multiple requests while it was building and sometimes those requests may have had conflicting "other" builds.... dunno.

In any case I've not had it go stale since I stopped doing that so I'm going to close this.
