### ISSUE TITLE
Prevent cookie handling from asset directories

### ISSUE THREAD

**Issue by Morgon** [jasonlewis/basset#23]
As I'm sure you know, session handling on asset URLs is very wasteful and resource-intensive. I don't know if there's something wrong with my particular install, but my asset bundles are going through the whole session interface. 

In Chrome, the response headers look like the following:

Request URL: http://dev.site:81/assets/bundle.css (I changed the route from basset to assets)

<pre>
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/css; charset=UTF-8
Server:nginx
Set-Cookie:session_payload=[Snip long string]; expires=Mon, 18-Jun-2012 01:55:59 GMT; path=/; httponly, appsession=[SessionData]; expires=Mon, 18-Jun-2012 01:55:59 GMT; path=/; httponly
Transfer-Encoding:chunked
cache-control:no-cache
date:Mon, 18 Jun 2012 00:55:59 GMT
</pre>

I do also find it interesting that cache-control is set to no-cache, which is a similar head-scratcher for me.
While I know I can change the session type so it doesn't set payload data, that's not the problem - basset shouldn't be doing any kind of session handling, if at all possible.

Is this a known issue? Is there something that can be set to prevent this from happening?

**Comment by jasonlewis** [comment]
Basset goes through the normal operations of Laravel. I can turn sessions off during the operation so perhaps that's the best option there.

I'm not too sure on the Cache Control actually because of new features implemented in Basset 2 that the caching could affect. Ideally it's up to developers to leverage the caching built-in.

**Comment by wildlyinaccurate** [comment]
@Morgon If your assets are being served up from the same domain as the website, the client will be sending its cookie headers anyway. Removing the Set-Cookie header won't really do anything for performance unless your assets are being served from another domain.

More info: https://developers.google.com/speed/docs/best-practices/request?hl=sv#ServeFromCookielessDomain

**Comment by wildlyinaccurate** [comment]
@Morgon Also, on the no-cache issue: since you're using nginx, you'll want something like this in your site config:

```
location ~* \.(?:css|js)$ {
    expires 1y;
    add_header Pragma public;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";
}
```
