### ISSUE TITLE
Dependency syntax when declaring assets

### ISSUE THREAD

**Issue by doginthehat** [jasonlewis/basset#24]
@jasonlewis Thanks for this library, it's pretty sweet..

I'm wondering if this kind of syntaxes could be added:

```
Basset::scripts('jquery', function($basset)
{
    $basset ->add('jquery',     'resources/third_party/jquery/1.7.2/jquery-1.7.2.min.js');
});

Basset::scripts('underscore', function($basset)
{
    $basset ->add('underscore', 'resources/third_party/underscore/1.3.3/underscore.js');
});

Basset::scripts('json2', function($basset)
{
    $basset ->add('json2',      'resources/third_party/json2/json2.js');
});

// then (re-use)
Basset::scripts('backbone', function($basset)
{
    $basset ->add('jquery')
            ->add('underscore')
            ->add('json2')
            ->add('backbone',       'resources/third_party/backbone/0.9.2/backbone.js');
});

// or (dependency format)
Basset::scripts('backbone', function($basset)
{
    $basset ->add('backbone',       'resources/third_party/backbone/0.9.2/backbone.js', array('jquery','underscore','json2'));
});
```

For big-ish project it would be nice to be able to reuse some definitions.

There is already some sort of dependency system but it only seems to apply to `inline()`

Or maybe there's already a way to do that?

**Comment by jasonlewis** [comment]
Hm, I'm not entirely sure this would be possible at the moment. But! Since I am yet to release Basset 2 I'll try to work it in when I get back into civilization. On the island at the moment, so not a lot of time (or good internet) to do any work.

**Comment by jasonlewis** [comment]
Hm toying with this now @doginthehat, at the moment I have it working like so:

```
Basset::scripts('first', function($basset)
{
    $basset->share('jquery', 'jquery.js');
});

Basset::scripts('second', function($basset)
{
    $basset->add('jquery')
           ->add('tooltip', 'tooltip.js');
});
```

So it all depends on hierarchy though. You must define the ones you will use later on first (of course). So the share method does not accept any dependencies since it's not needed (just a name and a file location). Then if you don't supply a file as the second parameter for add Basset will look for a shared asset of that name and use that instead.

Seem like a good solution?

Like you said the dependency system that is in place is the same as the Asset one which is bundled with Laravel and is primarily for inline assets.

**Comment by doginthehat** [comment]
@jasonlewis 

That could work, though maybe if the shared asset works as an independent pool of assets it could maybe done like this:

(note: i really don't know the inner workings, just throwing some ideas :)

```
Basset::share('jquery', 'jquery.js');

Basset::scripts('second', function($basset)
{
    $basset->add('jquery')
           ->add('tooltip', 'tooltip.js');
});
```

**Comment by jasonlewis** [comment]
@doginthehat, that is entirely possible I believe. The solution I posted above does add the shared asset to the current route to but sharing assets independently of routes is probably a better idea. I'll implement this now and get it ready for Basset 2.

Stay tuned. Also if you can, give the develop branch a whirl. It should be in a stable position at the moment.
