### ISSUE TITLE
Bug with Basset::inline

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#25]
I'm trying to setup a little build script for Laravel, and I would like to use Basset to concatenate and minify assets. The problem is, to interact with Basset I only have an array of scripts. So the only way I found to do this is the following :

``` php
<?php
$styles = Basset::inline('styles');
foreach($files as $file)
    $styles->add(File::name($file), $file);
```

The I thought I would fetch the resulting CSS and write it in a file as `styles.min.css` or something.
Unfortunately when I execute that code the following error is thrown :

```
Missing argument 1 for Basset\Container::__construct(), called in /Applications/MAMP/htdocs/CelsiusLaravel/bundles/basset/classes/basset.php on line 43 and definedMissing argument 1 for Basset\Container::__construct(), called in /Applications/MAMP/htdocs/CelsiusLaravel/bundles/basset/classes/basset.php on line 43 and defined
```

What am I doing wrong ?

**Comment by jasonlewis** [comment]
Sorry this appears to be a bug. I'll get a patch up as soon as I can. Thanks.

With the release of Basset 2, inline assets shouldn't really be needed as much as they used to be. Basset 2 allows you to adjust and create routes _anywhere_ in your application as long as it's done before the end of the request.

**Comment by jasonlewis** [comment]
Inline assets should now be working again in the 2.0.1 release.
