### ISSUE TITLE
Missing argument 1 for Basset\Container::__construct()

### ISSUE THREAD

**Issue by wildlyinaccurate** [jasonlewis/basset#26]
Normally I'd submit a patch but I can't figure out what the correct behaviour should be.

In `Basset::inline()`, a new `Basset\Container` is instantiated with no constructor arguments. (classes/basset.php, Line 43)

**Comment by jasonlewis** [comment]
Yeah thanks was made aware of this the other day. Should get this fixed up
soon, although like I said in the other issue, inline assets aren't really
needed anymore now that routes can be adjusted anywhere in your application.
On Jul 12, 2012 7:37 AM, "Joseph Wynn" <
reply@reply.github.com>
wrote:

**Comment by wildlyinaccurate** [comment]
Yeah true, although it's still nice to have the option. Cheers Jason!
