### ISSUE TITLE
Compressing assets

### ISSUE THREAD

**Issue by Meroje** [jasonlewis/basset#3]
Hi,
There is another problem with your class.

`Warning : extract() expects parameter 1 to be array, boolean given in /Applications/MAMP/htdocs/laravel/modules/basset/libraries/basset.php on line 503.`

```
#0 [internal function]: System\{closure}(2, 'extract() expec...', '/Applications/M...', 503, Array)
#1 /Applications/MAMP/htdocs/laravel/modules/basset/libraries/basset.php(503): extract(true, 3, 'compress_')
#2 /Applications/MAMP/htdocs/laravel/modules/basset/libraries/basset.php(478): Basset\Basset_Container->fetch()
#3 /Applications/MAMP/htdocs/laravel/modules/basset/libraries/basset.php(783): Basset\Basset_Container->render()
#4 /Applications/MAMP/htdocs/laravel/system/laravel.php(180): Basset\Basset_Container->__toString()
#5 /Applications/MAMP/htdocs/laravel/public/index.php(44): require('/Applications/M...')
#6 {main}
```

**Comment by jasonlewis** [comment]
THanks Meroje, I noticed this myself the other day. Hopefully I'll be able to push some fixes later. The compress() method needs to be changed to add an array similar to:

```
array(
    'css' => true,
    'js' => true
)
```

At the moment I believe it just sets the compress to true, which is how it used to do it.

**Comment by jasonlewis** [comment]
I'm going to close this as it's no longer being supported for Laravel 1.x (pretty sure it wasn't 2.x!). I'll get a bundle out for Laravel 3 shortly.

**Comment by Meroje** [comment]
I was about to ask if a bundle is on the way ! Thank you

2012/2/28 Jason Lewis <
reply@reply.github.com

**Comment by jasonlewis** [comment]
The develop branch is the bundle although not quite release ready but you're more than welcome to take a look. :)

**Comment by Meroje** [comment]
I'll look thank you, too much trouble with the session and the first basset
version.

2012/2/28 Jason Lewis <
reply@reply.github.com
