### ISSUE TITLE
Issues with directory

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#31]
I work in a self-contained bundle.
In my `start.php` I do the following to load the base assets :

``` php
<?php
// Base CSS
Basset::styles('styles', function($basset)
{
  $basset
    ->directory('public/bundles/reservation/css', function($basset)
    {
      $basset
        ->add('bootstrap', 'bootstrap.min.css')
        ->add('fontello',  'fontello.css')
        ->add('styles',    'styles.css');
    });
});
```

I tried simply giving directory `reservation::css` but it doesn't work. Same, the following :

``` php
<?php
Basset::scripts('scripts', function($basset)
{
  $basset
    ->add('datepicker', 'vendor/datepicker/js/bootstrap-datepicker.js')
    ->add('locale', 'vendor/datepicker/js/bootstrap-datepicker.fr.js')
    ;
});
```

Works fine. If I want to wrap it in a directory() to ease the process :

``` php
<?php
Basset::scripts('scripts', function($basset)
{
  $basset->directory('public/vendor/datepicker/js', function($basset)
  {
    $basset
      ->add('datepicker', 'bootstrap-datepicker.js')
      ->add('locale', 'bootstrap-datepicker.fr.js')
      ;
  });
});
```

It won't work unless I specifically prefix the argument with `public/`. ie. add() correctly looks in public/ as a base while directory() does not – which may impact the whole bundle thing.

**Comment by Anahkiasen** [comment]
My bad, just saw this was fixed in master/develop, thanks !

**Comment by jasonlewis** [comment]
I'll take a look at the bundle prefixing not working.

And are you saying that for directories it's not working unless you put
`public/` at the start? That's how directories work, it allows you to have
your assets anywhere outside the public directory.

You can use the `public:` helper which will use the path provided in
Laravel's paths.php file, in case paths change.
On Jul 25, 2012 5:59 PM, "Maxime Fabre" <
reply@reply.github.com>
wrote:
