### ISSUE TITLE
compiled assets duplicating when specifying own directory

### ISSUE THREAD

**Issue by michaeldim** [jasonlewis/basset#32]
I have an extended config file in my application folder which specifies my own compiled folder,

``` php
...
 'directory' => path('storage') . 'compiled',
...
```

In my routes.php I have, 

``` php
...
// Start Basset
Bundle::start('basset');

// Load Basset Config
Basset\Config::extend('basset');

// Set up styles
Basset::styles('styles', function($basset)
{
    // Assets available at the following route: localhost/basset/styles.css
    $basset->add('bootstrap-css', 'css/bootstrap/bootstrap.css')
        ->add('responsive', 'css/bootstrap/bootstrap-responsive.css')
        ->add('styles', 'css/styles.css');
});
...
```

However i've noticed that the files are compiling in both the basset bundle and in my storage folder.

**Comment by jasonlewis** [comment]
Thanks, I'll take a look at it today.

**Comment by jasonlewis** [comment]
Are you using the latest version of Basset? I am unable to reproduce this. Try pulling down the latest master and see if that fixes it.

**Comment by michaeldim** [comment]
I think the problem was the example routes.php in the basset bundle were compiling in addition to the ones in my application routes file.

**Comment by jasonlewis** [comment]
Ah yes, that makes sense. :)

**Comment by Anahkiasen** [comment]
Shouldn't those examples be removed or moved to block comments instead actually ? Everytime I set up Basset somewhere I have to empty the examples file which makes my git branch dirty. I think once you checkup the repo it should be usable as is, without having to remove/replace stuff.

**Comment by michaeldim** [comment]
@Anahkiasen I ended up doing the same, marking the examples as a block comment. So +1 to this idea.

**Comment by jasonlewis** [comment]
Yeah if it's being a pain I can do that, no worries.
