### ISSUE TITLE
Config:extend() causes error when artisan commands run

### ISSUE THREAD

**Issue by michaeldim** [jasonlewis/basset#35]
If I extend the config file [Basset\Config::extend('basset');] then whenever I run any artisan commands through the CLI I get this error appear in the command line:

``` code
Warning: array_merge(): Argument #3 is not an array in /Applications/MAMP/site/bundles/basset/classes/config.php on line 49
```

**Comment by jasonlewis** [comment]
I'm not sure what the exact problem is. But I've pushed a possible fix to the develop branch which you can try. It basically type casts the extended config. Really not sure at the moment, will have to test a bit more for this.
