### ISSUE TITLE
Image management like Casset

### ISSUE THREAD

**Issue by leeovery** [jasonlewis/basset#38]
Thanks for putting this together.

Are you planning on adding in img management like Casset has? I contributed to this and you have the option of rewriting filenames to include the file mtime for the purposes of browser caching.

What are your thoughts around adding image management to Basset?

Thanks

**Comment by jasonlewis** [comment]
That sounds interesting. I'm not entirely sure. Currently there is discussion of Basset becoming part of the core for L4 but we'll see. Perhaps we can try to work something in there.

**Comment by jasonlewis** [comment]
Image management is no longer planned for Basset. It's now similar in nature to the asset pipeline.
