### ISSUE TITLE
Basset doesnt work in custom file system structure

### ISSUE THREAD

**Issue by neoighodaro** [jasonlewis/basset#39]
I have been using Basset 2, and i noticed something, when i decided to restructure file system, it broke basset. I had all my laravel folders in document root as they are by default (I mean the: application,public,laravel,storage etc.) and use VirtualHost to point to the public folder as document root. WHile this worked fine, i ran into issues when i decided i wanted to have just two folders in my original document root. I created a folder and moved the application,storage,laravel,paths.php,artisan etc except the public folder. so i had a cleaner document root. This absolutely broke basset. I havent attempted to fix it as i dont really have spare time, but maybe im doing something wrong.

**Comment by jasonlewis** [comment]
You changed your paths in the `paths.php` file correctly? I'll have a look at re-creating this. I think I may have run into something similar.

Can you provide anymore insight into how it is "broken"? Does it throw errors?

Cheers!

**Comment by neoighodaro** [comment]
Honestly i reverted already to the originaal file structure and continued working with basset. Anyways heres what i initially did, i updated the original file structure shipped with laravel. Mine was now...

/public_html/
 [+]/public/
 [+]custom-application/
   [>>] application
   [>>] bundles
   [>>] laravel
   [>>] etc...
 paths.php
 artisan

And thats when basset refused to work.
