### ISSUE TITLE
Adding Lessphp support back?

### ISSUE THREAD

**Issue by ralf57** [jasonlewis/basset#4]
I am wondering why Lessphp support has been removed from the bundle.
That was one of the best features of the previous version....

**Comment by jasonlewis** [comment]
I didn't get around to testing it or anything, I'll get it in the develop branch shortly and you can check that out. I'll let you know when it's in there. I'll keep this issue open for a reminded.

**Comment by jasonlewis** [comment]
@ralf57 Check out the develop branch now. There has been a slight alteration in the API again, I'll run a few more tests tomorrow then merge with the master branch and tag v1.3.

You now define routes like so:

```
Basset::styles('website', function($basset)
{
    $basset->add('website', 'css/website.less');
});
```

Note that you must supply the path from the public directory to the asset. You can still prepend the bundle identifier though:

```
Basset::styles('website', function($basset)
{
    $basset->add('website', 'bundle::css/website.less');
});
```

**Comment by ralf57** [comment]
Thanks,
cannot test it out right now but I am glad you put it back.
The "bundle::" bundle identifier is great since you usually don't want the less files to reside in the public directory but only the compiled CSS's

**Comment by jasonlewis** [comment]
This actually assumes they are in the `public` directory as all paths are relative to the `public` directory.

**Comment by ralf57** [comment]
Hmmm, do you think it's possible to keep the .less files in a non public directory (let's say _bundles/bundlename/less_) and only publish the compiled css's? I don't see any reason to have the less files in public unless you want to use the client side compiler.

**Comment by jasonlewis** [comment]
@ralf57 I'll have tinker with it shortly, want to add a couple more things to it to make it more robust in terms of the caching. Make it more like Blade, only recompile when assets change. Have to think about that though.

Also, is it common to store .less files in a non public directory?

**Comment by ralf57** [comment]
About the recompile-if-needed, I think it's not really needed but you may want to look at Lessphp's "watch mode":
http://leafo.net/lessphp/docs/#command_line_interface.

> Also, is it common to store .less files in a non public directory?

Don't know if it's a common but I always store them in a private location since it doesn't make any sense to have them publicly accessible with the compiled css

**Comment by jasonlewis** [comment]
Recompiling when needed would be great for those that want to permanently
have compression enabled, that way when they change a file will the assets
be recompiled again. Caching can stay though I think. I didn't get s chance
to do much last night. Should be able to get this done soon though. Couple
days. :-)
On Apr 12, 2012 7:23 AM, "ralf57" <
reply@reply.github.com>
wrote:

**Comment by jasonlewis** [comment]
Issue is now resolved. See the latest version 1.3. Thanks!
