### ISSUE TITLE
Basset on Pagodabox?

### ISSUE THREAD

**Issue by neoighodaro** [jasonlewis/basset#40]
I recently deployed an app on Basset. Everything worked pretty nicely on localhost but when i pushed the app to pagodabox it didnt load the assets. And when i decide to view the routed css, it shows the /\* Basset could not find ... */ error. I had to use the <code>->development()</code> method chain to my Basset routes to get it to work.

This is my first time using Pagodabox so maybe im just not doing something right.

**Comment by michaeldim** [comment]
What have you got your compiled directory location as, is it to a writeable directory listed in your boxfile?

**Comment by neoighodaro** [comment]
Its the default compiled directory. Will try to find out how to do that and see if it works

**Comment by neoighodaro** [comment]
Thanks. closed.
