### ISSUE TITLE
Issue with latest Laravel

### ISSUE THREAD

**Issue by ralf57** [jasonlewis/basset#41]
First of all, thanks for this great useful bundle.
I cannot have it working with the latest Laravel (3.2.4) but honestly I didn't try with an older version.
After cloning and enabling Basset in a fresh Laravel installation, I put the following code to test:
_application/routes.php_

``` php
Route::filter('before', function()
{
    Bundle::start('basset');

    Basset::styles('main', function($basset)
    {
        $basset->directory('themes/test/css', function($basset)
    {
        $basset->add('main', 'main.css');
        });
    });
    return View::make('home.index');
});
```

then in the template _application/views/home/index.blade.php_ I have

``` php
{{ Basset::show('main.css') }}
```

When I load the page I get a 404 for that asset route:

``` php
http://localhost/test/laravel/public/basset/main.css
```

Some notes:
- the asset live outside of the public directory
- the asset gets compiled properly

Am I missing some step?
Please let me know if you need more details

cheers

**Comment by jasonlewis** [comment]
Thanks this should hopefully be now fixed in the develop branch!

**Comment by ralf57** [comment]
Thanks for the quick fix. It works great.
BTW, I am integrating Basset into [Lightgear's theme bundle](https://github.com/lightgear/theme).
The goal is to keep the Theme bundle as much general as possible so that it can be sent to bundles.laravel.com.
Will keep you posted.
