### ISSUE TITLE
Handle Coffeescript

### ISSUE THREAD

**Issue by thelinuxlich** [jasonlewis/basset#44]
It will be awesome if Basset handled Coffeescript in the same way it handles LESS, there is already a PHP Coffeescript compiler: https://github.com/alxlit/coffeescript-php

**Comment by dubcanada** [comment]
:thumbsup:

**Comment by jasonlewis** [comment]
Basset for L4 will support CoffeeScript thanks to the Assetic package.

The L3 version of Basset will eventually be updated to be the same. Cheers.
