### ISSUE TITLE
Handle SASS

### ISSUE THREAD

**Issue by thelinuxlich** [jasonlewis/basset#45]
Like the Coffeescript issue, but with SASS:
https://github.com/richthegeek/phpsass

**Comment by dubcanada** [comment]
Sadly the phpsass is terrible at best. Even the phpless isn't 100% but the phpless is at least at maybe 98%. phpsass doesn't even compile the sass homepage examples properly.

I would not really suggest adding sass...

**Comment by jasonlewis** [comment]
Same as the CoffeeScript issue, this will be added in in due time. Cheers.
