### ISSUE TITLE
Weird path correction

### ISSUE THREAD

**Issue by CoolGoose** [jasonlewis/basset#5]
I have ../../img in my css file as a path for an image, for some reason the generated path is 
http://localhost/personal/cms/public/assets/olgoose/Work/personal/cms/public/img/glyphicons-halflings.png
not
http://localhost/personal/cms/public/assets/coolgoose/Work/personal/cms/public/img/glyphicons-halflings.png

(it's olgoose instead of coolgoose).

Any ideas ? Thanks :)

**Comment by jasonlewis** [comment]
Hm, I can't take a look right this very minute. But I'll test this
afternoon. Can you give me your directory structure, or,at least a bit of
it so I can reproduce. Thanks!
On May 5, 2012 2:37 AM, "Alexandru Bucur" <
reply@reply.github.com>
wrote:

**Comment by CoolGoose** [comment]
laravel base path: /home/coolgoose/Work/personal/cms
laravel public path: /home/coolgoose/Work/personal/cms/public
css included /home/coolgoose/Work/personal/cms/public/css/admin/bootstrap.css
image from css it's (../../img) and it exists /home/coolgoose/Work/personal/cms/public/img

Basset is in a start/basset.php file 

``` php
Bundle::start('basset');

Basset::styles('public', function($basset)
{
    $basset->add('normalize', 'normalize.css');
});

Basset::styles('admin', function($basset)
{
    $basset->directory('public/css/admin', function($basset)
    {
        $basset->add('bootstrap', 'bootstrap.css')
               ->add('admin', 'admin.css')
               ->add('bootstrap-responsive', 'bootstrap-responsive.css');
    });
});

Basset::scripts('admin', function($basset)
{
    $basset->add('jquery', 'jquery-1.7.2.js')
           ->directory('public/js/bootstrap', function($basset)
            {
                $basset->add('bootstrap-alert', 'bootstrap-alert.js')
                       ->add('bootstrap-button', 'bootstrap-button.js')
                       ->add('bootstrap-carousel', 'bootstrap-carousel.js')
                       ->add('bootstrap-collapse', 'bootstrap-collapse.js')
                       ->add('bootstrap-dropdown', 'bootstrap-dropdown.js')
                       ->add('bootstrap-modal', 'bootstrap-modal.js')
                       ->add('bootstrap-popover', 'bootstrap-popover.js')
                       ->add('bootstrap-scrollspy', 'bootstrap-scrollspy.js')
                       ->add('bootstrap-tab', 'bootstrap-tab.js')
                       ->add('bootstrap-tooltip', 'bootstrap-tooltip.js')
                       ->add('bootstrap-transition', 'bootstrap-transition.js')
                       ->add('bootstrap-typeahead', 'bootstrap-typeahead.js');
            })
           ->add('admin', 'admin.js');
});
```

**Comment by jasonlewis** [comment]
Cheers I'll take a look right now. :)

**Comment by jasonlewis** [comment]
I'm unable to reproduce this. I've copied your directory structure and even nested the image multiple folders and the stylesheet multiple folders. Not sure why it's cutting out the first few letters. Is it only when you have the `../../` that it does this?

**Comment by CoolGoose** [comment]
No, it seems to do the same weird behaviour (removing co) also when trying to use less on the main bootstrap.less file (that does  all the imports).

Any pointers on where in the code i should look so I can debug it ?

Thanks

**Comment by jasonlewis** [comment]
I'd look around here: https://github.com/jasonlewis/basset/blob/master/basset.php#L448

It sounds like something to do with the rewriter for relative paths. Try dumping the file array and also looking at the contents. I'd just just testing with a single file and keeping it simple, such as a single image or something. Sorry for the inconvenience!

**Comment by CoolGoose** [comment]
Closing this, opened a pull request :)
