### ISSUE TITLE
Don't access container objects until booting

### ISSUE THREAD

**Issue by franzliedke** [jasonlewis/basset#54]
In the service provider, you have code like this:

```
$app['router']->before(function($request) use ($app)
{
    if ($app['basset.response']->verifyRequest() and $app['basset.response']->prepare())
    {
        return $app['basset.response']->getResponse();
    }
});
```

I would argue that this kind of stuff should be moved to the `boot()` method of the service provider.

This has two reasons:
1. Instantiate these objects as late as possible.
2. At boot time, all services should be registered, so you won't depend on the order of registration. That point is obviously more important (especially for the part where you access the events container).

**Comment by jasonlewis** [comment]
Yeah makes sense, I'll take a look after the weekend. Thanks Franz!

**Comment by franzliedke** [comment]
De nada. This looks promising. :)

**Comment by jasonlewis** [comment]
@franzliedke, at what stage is the `boot()` method fired for a provider?

**Comment by franzliedke** [comment]
Just before dispatching the route. So enough to still modify things or even
add routes.

Am Samstag, 1. Dezember 2012 schrieb Jason Lewis :

**Comment by jasonlewis** [comment]
This has been implemented @franzliedke. Cheers! :)

**Comment by franzliedke** [comment]
I'd argue the same goes for the call to the `events` object.

**Comment by jasonlewis** [comment]
Hm, I might have to remove the event entirely. Originally I planned on having it as another option for adding collections. The register method isn't a good place for it, as it's fired way to early in the execution. It appears as though the boot method is not fired from the command line.

Can you think of any other scenarios where you might want to tap into this event?

**Comment by franzliedke** [comment]
I don't really know, to be honest. Haven't looked at the package in that much detail. :)

But I'd guess for some other package requiring Basset it would be the perfect spot to set up some assets, no? Or, even better, for optionally supporting Basset (it would fail gracefully as the event would simply not be fired).
