### ISSUE TITLE
Assets name

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#57]
In Basset 3 you can define aliases for assets directories, but you can't seem to alias assets anymore like you could in Basset 2 with the `share` method.
This was a really useful function for defining one alias for an asset that you could then quickly add on several containers. Is there a way to achieve that in the new version ?

**Comment by jasonlewis** [comment]
Ah, I did remember this but must've forgotten it. If it's that useful I'll pop it back in.

**Comment by Anahkiasen** [comment]
Maybe via an simple array in the config file like for directories ? And then check for `name:` in the `add()` method. Don't know how your code is or if it's difficult.

**Comment by jasonlewis** [comment]
Yup, sounds reasonable. I'll also add back in the `Basset::share()` method, although it'll be a bit more descriptive: `Basset::shareAsset()`

**Comment by jasonlewis** [comment]
I've gone with `Basset::aliasAsset()`, it's on the master branch for L4. Will move it across to L3-develop tomorrow, out of time now.

**Comment by Anahkiasen** [comment]
Okay no problem, thanks a lot !
