### ISSUE TITLE
Problem with dynamically generated assets handling

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#59]
Basset before adding any asset check its existence with a `file_exists`. This creates a problem with dynamically generated assets like the former **Glow** javascript helper that used to be in the Illuminate packages :

``` php
Route::get('glow.js', function() {

  // Get Glow's file
  $js = File::get('public/bundles/cerberus/js/glow.js');

  // Replace variables
  $js = str_replace('%BASE%', URL::base().'/', $js);
  $js = str_replace('%ASSET%', URL::to_asset(''), $js);

  // Set correct header
  $headers['Content-Type'] = 'application/javascript; charset=utf-8';

  return new Response($js, 200, $headers);
});
```

As the asset doesn't exist per se but is generated on viewing, Basset can't find it and thus doesn't cache it. For some reason those assets used to work on Basset 2 so I don't know what changed between the two.

**Comment by jasonlewis** [comment]
Hm, yeah I  can see the problem. I think your best bet here would be to try and use an absolute URL to the asset. That way it would be detected as a remote asset and would be excluded from the existence check.

```
$collection->add('http://yoursite.local/glow.js');
```

**Comment by Anahkiasen** [comment]
Hm... it does skip the existence check, but comes compiling time the file is still missing from the final javascript. Tried with both an absolute local URL and an absolute remote URL.

**Comment by jasonlewis** [comment]
I just pushed another commit @Anahkiasen, it seems that Laravel's `File::get()` does a `file_exists()` as well, so I'm using PHPs `file_get_contents()` directly now. Let me know if this fixes the problem.

**Comment by Anahkiasen** [comment]
Yup, it works now. And yeah `File::get` also does a check, Taylor even added a [File::getRemote](https://github.com/illuminate/filesystem/blob/master/src/Illuminate/Filesystem.php) function in Laravel 4 that basically just does a `file_get_contents` without the file check because people ran into the same issue.

**Comment by jasonlewis** [comment]
Yeah I'm using `getRemote()` in Basset's package for Laravel 4. =)
