### ISSUE TITLE
Filters not forcing recompile

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#60]
Say I define the following container and compile it : 

``` php
Basset::collection('carousel', function($collection) {
  $collection->add('components/bootstrap/js/bootstrap-carousel.js');
  $collection->add('app/js/carousel-setup.js');
});
```

Everything goes smooth, now I want to minify that javascript :

``` php
Basset::collection('carousel', function($collection) {
  $collection->add('components/bootstrap/js/bootstrap-carousel.js');
  $collection->add('app/js/carousel-setup.js');
})->apply('GoogleClosure\CompilerApiFilter');
```

I get the following message : `The scripts for the collection 'carousel' do not need to be compiled.`. Adding filters to a container (didn't check if the same happened for individual assets) doesn't retrigger compilation so I had to empty the `assets` folder.

Don't know if that's a bug or wanted behavior.

**Comment by jasonlewis** [comment]
Yup, this is a bug. Thanks I'll patch this ASAP.

**Comment by jasonlewis** [comment]
That push should fix this one for you @Anahkiasen.

**Comment by Anahkiasen** [comment]
Yup works fine now, thanks !
