### ISSUE TITLE
Throw exceptions when asset is not found.

### ISSUE THREAD

**Issue by jasonlewis** [jasonlewis/basset#61]
Because sometimes you may try to chain filter methods after adding an asset it'd be best if an exception was thrown if assets could not be found.

**Comment by Anahkiasen** [comment]
When using the `list` command, a warning with the number of assets not found would be great too, as currently Basset might tell you it found styles or scripts (which it probably indeed did) but doesn't tell you it might also have skipped missing assets in the process.

**Comment by jasonlewis** [comment]
Hm, yeah I'll have to think about this one. Can you open a separate issue for that? Thanks.

**Comment by Anahkiasen** [comment]
Well actually you added an exception in b1aa114485aa11afa7824b61a491041b5914d665 so it's now ok, warnings are thrown about missing assets.
