### ISSUE TITLE
Filters not applied to collections as a whole

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#65]
Still on Laravel 3 – when I do the following, assets are minified just fine :

``` php
Basset::collection('slider', function($basset) {
  $basset->requireDirectory('app/js/models')->apply('JsMin');
  $basset->add('app/js/modules/slider.js')->apply('JsMin');
});
```

However this returns unminified Javascript in the final file :

``` php
Basset::collection('slider', function($basset) {
  $basset->requireDirectory('app/js/models');
  $basset->add('app/js/modules/slider.js');
})->apply('JsMin');
```

`JsMin` is here an alias for Closure's minifier, does it maybe come from here ? Do I need to use the full name ?

---

**UPDATE** Ok now even applied on a file-basis it works but not all the time. The filters are kind of random I'm noticing.

**Comment by jasonlewis** [comment]
Hm this could be something to do with the API throwing back incorrect results. Is this for all or only the Google Closure filter?

**Comment by Anahkiasen** [comment]
Well I'm aware of Closure's usage limits but I think I already got that message once and it displayed correctly. Here the filter fails silently, which is kind of weird.
I'll try another filter and update this.

**Comment by jasonlewis** [comment]
Cheers, that's my only guess at the moment. I'll have to take a look at some point as it could be directly related to the L3 version. I need to give it a good once over to iron everything out.

**Comment by stevenwoodson** [comment]
I noticed this happening with my trying to use CSSMin but I'm using the L4 variety, What ended up working for me was something like this in the config.php file:

```
'website' => function($collection) {
    $collection->add('vendor/bootstrap.css');
    $collection->add('vendor/bootstrap-responsive.css');
    $collection->add('vendor/zebra_datepicker.css');
    $collection->add('webfonts/ss-symbolicons-block.css');
    $collection->add('main.scss')->apply('ScssphpFilter');
    $collection->apply('CssMinFilter');
}
```

Not sure if it helps but wanted to share just in case.

**Comment by jasonlewis** [comment]
The way filters are applied has slightly changed and should work a whole lot better. So I'm hoping this is resolved in my local copy. Should have something out on the weekend (if all goes well). I'll leave this open until such time as we're sure it's fine.

**Comment by Anahkiasen** [comment]
Why keeping it all local all t his time, why not just create a branch ? Now you're gonna release a hundred-commits update and if it all stops working for various people you'll bang your head out trying to figure out where it broke.

**Comment by jasonlewis** [comment]
Unfortunately some people will have problems and I'm expecting everyone
will need to re-install it. It isn't really an upgrade job. Fresh checkout
will be needed.

**Comment by Anahkiasen** [comment]
Will the API change a lot ?

**Comment by jasonlewis** [comment]
No, there are some slight changes but I'll have everything documented.
It'll be worth it.

**Comment by radmen** [comment]
What about this issue? I spend few hours to discover that `apply()` needs to be run in `directory()` callback, not on the returned instance (I'm using standard L4 Basset config).

**Comment by jasonlewis** [comment]
On the develop branch collections can be filtered as a whole.

**Comment by rcrowe** [comment]
I'm still seeing this issue. Calling `$directory->apply('JsMin')` has no effect.

While I can get it to work if called on the collection, this courses all sorts of issues when also minifying css within the same collection.

**Comment by rcrowe** [comment]
Scrap that. After using the config example on the README I got it working. It seems the example in the config file doesn't work correctly.

**Comment by jasonlewis** [comment]
The example in the `config/config.php` file, meaning the default `application` collection? It should be working as it has the filter aliases defined. If you've overwritten the filter aliases then using `JsMin` won't work, you'll need to use `JsMinFilter` as that's the non aliased name.

**Comment by jasonlewis** [comment]
Going to close this for now.
