### ISSUE TITLE
Trying to use version 4.* resulting in Your requirements could not be resolved

### ISSUE THREAD

**Issue by andrew13** [jasonlewis/basset#69]
Trying to use version 4.\* resulting in Your requirements could not be resolved to an installable set of packages.    Problem 1     - The requested package jasonlewis/basset 4.\* could not be found. 

Any ideas on what I'm doing wrong.

My composr.json file

{
    "require": {
        "illuminate/foundation": "1.2._",
        "jasonlewis/basset": "4._"
    },
    "autoload": {
        "classmap": [
            "app/controllers",
            "app/models",
            "app/database/migrations",
            "app/tests/TestCase.php"
        ]
    },
    "minimum-stability": "dev"
}

**Comment by jasonlewis** [comment]
Hey sorry but I haven't actually tagged any versions yet so you'll need to use `"jasonlewis/basset": "*"` for the time being. I wasn't planning on tagging anything until L4 has been officially released as things could still change.

**Comment by andrew13** [comment]
Makes sense. You might want to update http://jasonlewis.me/code/basset with that just so others don't do the same thing I did. Thanks for the help

**Comment by jasonlewis** [comment]
It is mentioned underneath in italics.

> Note that Basset is still being developed at the time of writing so you may need to use "*" instead.
