### ISSUE TITLE
Not working with latest L4 beta release

### ISSUE THREAD

**Issue by raftalks** [jasonlewis/basset#71]
I think you will need to change the dependency on illuminate repo to laravel/framework repo.

https://github.com/jasonlewis/basset/blob/master/composer.json#L16-L21

need to be updated

**Comment by jasonlewis** [comment]
I'm not so sure, but will look into this. Going to wait for the dust to settle a bit and the beta to be actually released as there has been no official word yet. It's a bit of a waiting game at the moment I'm afraid.

**Comment by Anahkiasen** [comment]
This is fixed now no ? Basset's working well for me on latest.

**Comment by jasonlewis** [comment]
Be aware things will break and that Basset itself is changing again. API should stay the same for the most part.
