### ISSUE TITLE
Auto compile (in development)

### ISSUE THREAD

**Issue by barryvdh** [jasonlewis/basset#73]
As I understand correctly, the new approach doesn't automatically compile assets?
So every time I change something, I should run compile via Artisan?
I know I can do something like 

```
Route::get('compile', function(){
    \Laravel\CLI\Command::run(array('basset::compile'));
});
```

To go to /compile and rebuild, but this is an extra unnecessary step..

Is it possible to check for change file maketime? Or maybe check if the compiled file exists, and if not, recompile?
(Using L3-develop btw)

**Comment by barryvdh** [comment]
Additional information: the compile is required because of my LessPhpFilter. Without that filter, it serves plain .less, so the website is unusable..

**Comment by aksonnic** [comment]
Rather than doing a full compile, in dev mode it should at least process individual files through filters (minification would have to be handled differently, I think).
