### ISSUE TITLE
CDN/Remotes & Assets

### ISSUE THREAD

**Issue by wouterbulten** [jasonlewis/basset#77]
When I add remote sources they are correctly detected and loaded by Basset. In my development environment they are included like you would expect.

However, when running 'compile' they are compiled and stored locally. Any ways to disable this behaviour or to force loading from the remote? As compiling these static (remote hosted) files would be counter-beneficial.

**Comment by jasonlewis** [comment]
The only way would be to place them in a separate collection and not compile that collection.

**Comment by wouterbulten** [comment]
Is this possible from within the Basset setup? (So that it is automatically skipped during compilation)

**Comment by jasonlewis** [comment]
I'm going to put this on my todo list as I might have an idea of how it can be implemented. I'll keep you informed.

**Comment by wouterbulten** [comment]
Great! I now use a workaround by keeping a list of 'cdn assets' in my config. It would be great if Basset could support this so we can use a single system.

**Comment by jasonlewis** [comment]
Dealing with remote assets is greatly improved for the upcoming release. Remotes are now excluded by default, however you can include them if you wish.

**Comment by betawax** [comment]
@jasonlewis, how should I handle collections in L4 that only contain remote assets? For example:

``` php
'datepicker' => function($collection)
{

    $collection->add('http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css');
    $collection->add('http://code.jquery.com/ui/1.10.2/jquery-ui.js');

},
```

This will include the assets from the remote CDN and ignore them in the build process as expected, but Basset still tries to include a `datepicker-8172119cc5e0bd28c3dbdfd8648ae4c5.css` and `datepicker-15dda11c6f8ebac8990e428fbc97f13e.js`for the collection which results in two `404 Not Found`.

**Comment by jasonlewis** [comment]
Ah does it! Good pickup. I'll open an issue for this so I remember. That's a bug.
