### ISSUE TITLE
Assets not found prevent packages assets from publishing

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#78]
Currently as Basset not finding an asset throws an exception, this prevents artisan from publishing a package's assets — as they are not in the public folder they can't be found but can't be published to the public folder since it throws an exception.

**Comment by jasonlewis** [comment]
For the upcoming changes I'll be sure to deal with exceptions in a friendlier way.

**Comment by jasonlewis** [comment]
This has been fixed in the unreleased version.
