### ISSUE TITLE
Filter throws an Exception

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#81]
I get the following error when trying to compile with the PackerFilter :

```
ReflectionException: Class Assetic\Filter\PackerFilter does not have a constructor, so you cannot pass any constructor arguments
in /htdocs/public/www/vendor/jasonlewis/basset/src/Basset/Asset.php line 222
```

Apparently Basset tries to pass arguments to the PackerFilter class via a ReflectionClass and the latter throws an exception since PackerFilter doesn't have any constructor.

**Comment by jasonlewis** [comment]
Yucky. It's on the list. Thanks @Anahkiasen.

**Comment by jasonlewis** [comment]
This should now be fixed in the still unreleased version. Thanks.
