### ISSUE TITLE
->directory not working

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#82]
The following throws an exception with me :

``` php
$collection->directory('components/rainbow/js', function($collection) {
  $collection->add('rainbow.min.js');
  $collection->add('language/generic.js');
  $collection->add('language/php.js');
});
```

Paths are all valid and files exist, manually pointing to the full path of each one works. But `->directory` doesn't – it seems to set a `$directory` attribute on the class that is never once used in `->add` or any other method – it only looks in `public`.

**Comment by Anahkiasen** [comment]
Ok my bad : `->directory` assumes you prefix paths with `public` while `->add` doesn't. Should be mentionned in the docs though.

**Comment by jasonlewis** [comment]
Yeah I'll be sure to mention this. I'm going to assume by default that paths are relative from public in future versions though.
