### ISSUE TITLE
Basset::show error

### ISSUE THREAD

**Issue by Globegitter** [jasonlewis/basset#83]
I wrote about something similar a couple weeks back (in the laravel forum), but I kinda ran into a different error this time (focused on another project over the last few weeks). so.
I have the ollowing in the config.php

'collections' => array(
        'main' => function($collection){
            $collection->add('path: ../vendor/twitter/bootstrap/less/bootstrap.less')->apply('LessphpFilter');
        },
    )

and in the main html file I have

{{ Basset::show('main.css') }}

The compiling works, I get the main.css in the public/assets folder, but there is an issue,
I literally see <link rel="stylesheet" href="http://localhost/wbw-l4/public/assets/main-d5ca88f35b5482330f20a8c359a3bda6.css"> 
encoded as a string on the website instead of it being encoded as html and linking to the css file. Anyone any idea what this could be? Help would be really appreciated.
Cheers

**Comment by Anahkiasen** [comment]
That's because of a recent change to the Laravel 4 API : all strings echoed out with `{{ }}` are now encoded by convention over other templating systems. You need to use `{{{ }}}` to let the content being printed unfiltered.

**Comment by Globegitter** [comment]
Ah, works beautifully. Cheers
