### ISSUE TITLE
Support for csso

### ISSUE THREAD

**Issue by Globegitter** [jasonlewis/basset#84]
Would it be possible to add https://github.com/css/csso as a filter? Not that super important, but would be quite nice and helpful to have as well to choose from.
Or is there any easy way of implementing it maually?
Cheers

**Comment by barryvdh** [comment]
Basset is based on Assetic, so you can write your filter for that, just implement the FilterInterface. See https://github.com/kriswallsmith/assetic/tree/master/src/Assetic/Filter for the interface and different examples. You could probably modify CssMinFilter to use CSSO.

**Comment by jasonlewis** [comment]
I'll keep this in mind and might bundle a filter.

**Comment by Globegitter** [comment]
That would be brilliant, Jason. I might try to have a look at it myself at some point, but time-wise it is not looking great currently. So yep, would be really appreciated.

**Comment by jasonlewis** [comment]
This has been implemented in the yet to be released version. Thanks!
