### ISSUE TITLE
L4 requires "4.*" or "dev-master" ?

### ISSUE THREAD

**Issue by Bulmer** [jasonlewis/basset#85]
I've found conflicts in your docs for L4 requirements. Which one should I use? If I use "4._" I get a "The requested package jasonlewis/basset 4._ could not be found" in Composer.

**Comment by barryvdh** [comment]
dev-master

**Comment by jasonlewis** [comment]
Yes the docs say to use `4.*` however there is a note saying that it may not work as Basset is still in development. Use `dev-master` for now.
