### ISSUE TITLE
Code example for using assets in views not working anymore

### ISSUE THREAD

**Issue by betawax** [jasonlewis/basset#86]
Your code example for using assets in views is not working anymore because of the latest changes on how Blade escapes output in Laravel 4.

I refer to the section _USING ASSETS IN VIEWS_ for Basset 4 here:
http://jasonlewis.me/code/basset

The following

``` php
{{ Basset::show('website.css') }}
```

must be changed to

``` php
{{{ Basset::show('website.css') }}}
```

to get the raw output.

> Blade {{ }} now escapes by default. {{{ }}} for raw output.

See: https://github.com/laravel/framework/issues/206

**Comment by jasonlewis** [comment]
Thanks, will update this when the docs are refreshed for the upcoming changes to Basset.
