### ISSUE TITLE
Using directories fails

### ISSUE THREAD

**Issue by andheiberg** [jasonlewis/basset#88]
In order to get terminal command 'php artisan basset:compile' to work I have to do the following in my config.php

```
'directories' => [
    'css' => 'path: public/assets/css',
    'js' => 'path: public/assets/js',
],
```

But then when using 'basset::show()' I get the following error:

```
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/public/assets/css): failed to open dir: No such file or directory
```

Coincidentally the same I get in terminal if I set my config.php file like so:

```
'directories' => [
    'css' => 'path: assets/css',
    'js' => 'path: assets/js',
],
```

Which in return resolves the error when using 'basset::show()'

**Comment by jasonlewis** [comment]
Drop the path: prefix, that's only needed if you're defining an absolute
path to your directories. Directories are relative from the root of your
application. Keep in mind this will change and will be relative from the
public directory.

**Comment by andheiberg** [comment]
Thanks! It might just be me that overlooked it, but I think you should change the inline documentation so that it says 

```
| array(
|    'css' => '/relative/path/to/your/directory/form/public'
| )
```

and then say there is an option to make it relative by using path:

Again it might just be me, but I think this will rule out any misconceptions
