### ISSUE TITLE
Prefix for UriRewriteFilter

### ISSUE THREAD

**Issue by barryvdh** [jasonlewis/basset#89]
When the website is in a subfolder, you should have to possibility to define a prefix in your configfile (so you can set different prefixes for different environments).

**Comment by jasonlewis** [comment]
I'm not sure I follow you. Can you show me an example?

**Comment by barryvdh** [comment]
On my local server:
192.168.0.100/myproject/index.php
On my production-server:
myproject.com/index.php

The UriRewriteFilter rewrites the assets to /assets/style.css. This is correct for the production server, but the local server should be /myproject/assets/style.css
If it would be possibly to include an (optional) prefix / subdirectory to the UriRewriteFilter, this could easily be solved.

**Comment by jasonlewis** [comment]
How are you using the filter? Can you paste your code please.

**Comment by barryvdh** [comment]
Hm, I was using it like this:

```
'filters' => array(
        'UriRewrite' => array(
            'UriRewriteFilter' => array('public')
        )
    )
```

I have this layout in the public folder:
assets (compiled from basset)
less(original style.less)
fonts (my fonts)

Font references go from:
`src: url('../fonts/dosis-bold-webfont.eot');`(relative from the less folder)
to `src:url('/fonts/dosis-bold-webfont.eot');`
This works fine. But when I do the same on local, I get
`src: url('myproject/public/fonts/dosis-bold-webfont.eot');`

I alos tried using path('public') instead of just 'public', but that gives the same result (on local, fails on the real server).

**Comment by barryvdh** [comment]
Sorry, I also get `src: url('/fonts/dosis-bold-webfont.eot');` when using array('public'). The result before was from using path('public')
But that should be `/myproject/fonts/..` to make it work. So they are bot 1 level wrong.

**Comment by jasonlewis** [comment]
Hm, I'm testing this and it's working fine for me, although I'm using the current code which I am yet to release.

You should be using an absolute path (the full path to the public directory), which is indeed `path('public')`.

Can you give me an example of your directory structure. And is this on L3 or L4? I need as much information you can give me so I can recreate this.

**Comment by barryvdh** [comment]
L4 with the regular laravel folder layout. I now see that path('public') creates a path to public, so I should be using `array(base_path().'/public')` instead I guess.
I am using a symlink to reference my project, don't know if that matters.

Real public dir: `/home/projects/myproject/public`
Symlink to the public dir is: `/var/www/html/myproject`
So 192.168.0.100/myproject displays the public folder.
base_path() given by L4: `/home/projects/myproject/bootstrap/..`

In public I have `assets` and `css` and `img`. Test css file from public/css/test.css:

```
body{
    background: url('../img/img.jpg');
}
```

Rewrites to http://192.168.0.100/myproject/assets/style-3afcae26f4da2debfbfff40db92bfac5.css:

body{
    background: url('/img/img.jpg');
}

But in order for it to work it should be /myrpoject/img/img.jpg or ../img/img.jpg (so in this case rewrite isn't actually needed)

**Comment by jasonlewis** [comment]
Ah, symlinks. It isn't documented but you actually can pass in an array of symlinks to `UriRewriteFilter`. Try this:

``` php
'UriRewriteFilter' => array(null, array('//myproject', '/home/projects/myproject/public'))
```

While the docs aren't good for the original UriRewriter, take a look: https://github.com/mrclay/minify/blob/master/min/lib/Minify/CSS/UriRewriter.php#L32

I'm not 100% but you may not have to give a path. Otherwise, try using `base_path().'/public'`.

**Comment by barryvdh** [comment]
Hmm, can't really seem to get it working correctly. For the time being I changed it manually. Will try it again when you release your new version.

**Comment by barryvdh** [comment]
How do you pass the arguments to the filter in the new develop branch? And can't you use public_path() instead of  $_SERVER['DOCUMENT_ROOT'] by default?

**Comment by jasonlewis** [comment]
The example in the develop branch read me shows how to set arguments. Once
you've applied a filter you get an instance of Basset\Filter\Filter, you
can call setArguments() on this instance. It accepts any number of
parameters as is required by the filter.

**Comment by barryvdh** [comment]
Ah, missed that bit, tnx.
I did ran in to the same problem, because url's are written to /img etc, but I guess that is by design. I copied and changed the UriRewriteFilter to an additional UriPrependFilter (seeing that mrclay also added that option..)

```
$filter->apply('UriRewriteFilter')->setArguments(public_path())->apply('UriPrependFilter')->onEnvironment('local')->setArguments('/myproject');
```

Works great! (So far)

**Comment by jasonlewis** [comment]
My rewrite is does the same as his and I'm sure I've had it working with
symlinks. I'll do a screencast next week on Basset and how it's best used.
Probably do a couple.

If you have any other problems with the develop branch please let me know
(preferably in a new issue), cheers mate!

**Comment by barryvdh** [comment]
Yeah but the problem isn't the symlinks (if I just use public_path() instead of the $_SERVER['DOCUMENT_ROOT']).

But to clarify, the expected behaviour is to rewrite links like  "../img/test.jpg" to "/img/test.jpg", correct?
So if I'm testing my local site on 127.0.0.1/myproject als public folder, a link to /img will lead to 127.0.0.1/img, not 127.0.0.1/myproject/img obviously, that's why I needed an prefix option.

In the original class there also is prepend() function, besides the rewrite() function, that does just this.

**Comment by jasonlewis** [comment]
I'll look into it. Thanks!
