### ISSUE TITLE
less - Broken in v1.4 due to missing config/settings reference

### ISSUE THREAD

**Issue by t2t2** [jasonlewis/basset#9]
Basically add a .less file to styles:

``` php
$basset->add('style', 'style.less');
```

And you get an error:

```
Unhandled Exception
Message:

Undefined property: Basset\Asset::$settings

Location:

[...]bundles\basset\classes\asset.php on line 135
```

**Comment by jasonlewis** [comment]
I've just pushed what I hope is a fix to the **develop** branch because I am unable to test at this time. Hopefully I can get on later tonight and check it all out and merge it into the master. Let me know how you go!

Thanks.

**Comment by t2t2** [comment]
It's working for me now. Thanks!

**Comment by jasonlewis** [comment]
Great! I'll have to merge this with master and tag it as soon as I can.
Thanks!
On May 23, 2012 5:58 AM, "t2t2" <
reply@reply.github.com>
wrote:
