### ISSUE TITLE
Bundle a Default Collection

### ISSUE THREAD

**Issue by jasonlewis** [jasonlewis/basset#90]
Bundle a default collection so that Basset works immediately after installation without any setting up.

**Comment by Anahkiasen** [comment]
I don't get it, what would be in the collection ?

**Comment by jasonlewis** [comment]
The default collection will be the `application` collection. This will essentially be its signature.

``` php
Basset::collection('application', function($collection)
{
    $collection->directory('../app/assets/stylesheets', function($collection)
    {
        $collection->requireDirectory('less')->apply('LessFilter');
        $collection->requireDirectory('sass')->apply('Sass\ScssFilter');
        $collection->requireDirectory();
    })->apply('UriRewriteFilter');

    $collection->requireDirectory('../app/assets/javascripts/coffeescript')->apply('CoffeeScriptFilter');
    $collection->requireDirectory('../app/assets/javascripts');
});
```

That's just rough and not the actual signature but you get the idea. Basically this collection makes many assumptions of a pretty standard setup. It requires a number of directories and applies some filters to each of the directories so that the correct output is generated.

This is great if you use a similar or the same setup and want to get started with Basset. Assuming you're not doing anything funny like using symlinks it should work as soon as you require and install Basset.

If you don't want the default collection it can be disabled or removed entirely.
