### ISSUE TITLE
filter not ready yet?

### ISSUE THREAD

**Issue by liweihan** [jasonlewis/basset#93]
Hi 
Im trying to add filter to assets
$collection->requireDirectory('js/global')->apply('JSMinFilter');
I downloaded the filters from Assetic package
but I got Class 'JSMin'/'CssMin' not found errors
is filtering not ready yet?
thanks

**Comment by Anahkiasen** [comment]
Those are special libraries not included in Assetic, you need to add them to your dependencies via Composer.
Here is [CssMin](https://packagist.org/packages/natxet/CssMin) per example.

**Comment by liweihan** [comment]
wow yes it works! thanks @Anahkiasen 
btw, it should be pointed out in docs I think :)
@jasonlewis

**Comment by jasonlewis** [comment]
The docs will be re-worked and read as actual docs eventually. Bare with me. :smile:
