### ISSUE TITLE
Feature Request - Auto-compile and delete of old compiled files

### ISSUE THREAD

**Issue by stevenwoodson** [jasonlewis/basset#94]
I've got the L4 version of this package working with no problems, thanks for working this up for us Jason! I only had a couple nice-to-haves that I was wondering about, I (like many others) came to Laravel from CodeIgniter and got really used to the asset spark from @bstrahija https://github.com/bstrahija/assets. That CI spark was able to auto compile depending on whether the assets were updated and I believe would even remove the old compiled file that was being replaced. Would something like that be possible with this package?

**Comment by jasonlewis** [comment]
Hey mate this is resolved (kind of) in my local copy.

Basically the workflow is as follows: Basset will first look for a built and fingerprinted collection. If found and if running within a production environment it will use the built collection. If it wasn't found or the application is not running in a production environment it will dynamically build the collection on the fly, although each asset will be linked to individually to maintain a better debugging experience with tools like Firebug.

When you deploy to production you will still need to setup a post-deployment hook of some kind to build the collections as Basset won't build collections on the fly for a production environment. You can, of course, build collections prior to deployment and it will still work fine.

But as far as development goes there is no need to be building the collections as everything is dynamically built and generated.

**Comment by stevenwoodson** [comment]
Sounds like you've done just about exactly what I was dreaming of, are you hoping to release these changes soon? Can't wait, thanks again!
