### ISSUE TITLE
[Suggestion] Add option to gzip when compiling assets

### ISSUE THREAD

**Issue by ghost** [jasonlewis/basset#96]
Since we're already compiling assets, we could pre-gzip them too. This is something that is an option in the Rails asset pipeline as well.

The advantage of serving pre-gzipped assets, instead of gzipping on the fly when the assets are served, is that you can gzip using the highest compression (9), since we don't have to worry about CPU usage or the time it takes, allowing you to have the smallest file size possible.

This would have to be optional since it requires the developer to configure their server to serve these gzipped assets directly. For example, I'd set up Nginx not to gzip any content served from my /assets directory, which I would use only for my compiled / pre-minified & pre-gzipped assets. That would be so fast!

My initial thought to do this would be to use a `--gzip` option on the compile command. But it might also be nice to have a way to set this permanently within Basset's config, if possible, (e.g. 'gzip' => true) so that you could set it and forget it and know it'll always be done.

The files would use the same normal extension as normal (.css, .js) ([don't output with the .gz extension](http://webmasters.stackexchange.com/a/26049)). So nothing would change in how Basset output the URLs to the views either. A user could just turn it on or off depending on how their server is configured. The important thing would be just to make sure that the gzipped files have their header's content encoding set to indicate that it's compressed content (which PHP probably does automatically when gzipping file, I'm not certain though, would just have to try it and see.)

Add a CDN and the end result is the fastest possible way to serve static assets.

What do you think?

**Comment by jasonlewis** [comment]
Sounds great! I'll look into this, thanks mate.

**Comment by jasonlewis** [comment]
So I'm working this in at the moment @j20.

> This would have to be optional since it requires the developer to configure their server to serve these gzipped assets directly. For example, I'd set up Nginx not to gzip any content served from my /assets directory, which I would use only for my compiled / pre-minified & pre-gzipped assets. That would be so fast!

Does gzip not like it when you try to gzip something that's already gzipped? I was thinking of using a `--no-gzip` flag to disable it when you don't need it. This would be mentioned in the docs. Basically I want Basset to work at its best as soon as you install it and require minimal setting up. Convention over configuration basically.

Let me know mate! Thanks.

**Comment by jasonlewis** [comment]
On development assets are also dynamically generated. Do you think it's worthwhile to gzip the assets here as well, but perhaps using a level of 1 or 2?

**Comment by ghost** [comment]
I think gzipping a file twice would cause problems because the browser would try to decode (ungzip) the file and would still see encoded gibberish. So I think this particular feature should probably default to being off. Then the optimizers among us, like you and me, can turn it on and remember that they also need to set up their web server not to gzip these particular assets again. Defaulting to the non-gzipped version would work out of the box for everyone no matter how their server is configured. 

Hmmm That's a good question about local development. I'm not familiar with how Basset works. But my instinct is to say just keep it as simple as possible; probably best not to gzip anything unless you're serving compiled assets that the user has set to be gzipped. This way people can keep their development environments as simple and vanilla as possible. Performance doesn't matter much on the dev environment, but keeping it simple does.

**Comment by jasonlewis** [comment]
Ah yeah that's probably true. I'll run some tests and see what happens though.

And yeah I decided not to implement it for development. Just some extra overhead that isn't really needed as assets are built for every request. Will finish off the implementation today.

**Comment by ghost** [comment]
Awesome! Looking forward to trying it.

**Comment by jasonlewis** [comment]
I forgot to update this but this has been done in the develop branch.

**Comment by ghost** [comment]
Awesome. Thanks!
