### ISSUE TITLE
Slowing down L4 install

### ISSUE THREAD

**Issue by andheiberg** [jasonlewis/basset#97]
Just wanted to give you a heads up. When using basset on a local enviroment atleast, where you are not getting the compiled assets it would seam that basset is checking each file on each load. This can cause very slow loads if the scripts are unavailable or needs to be downloaded from a server (since you are effectively downloading assets twice once in browser and once on the server).

I had trouble with this and experience 2.7 sec added response delay as a result.

**Comment by jasonlewis** [comment]
This will no longer be a problem as the collection isn't evaluated until its used to actually output the collection. Before I release the most recent changes I'll be doing some benchmarks. Cheers mate!
