### ISSUE TITLE
type="text/javascript" could be removed

### ISSUE THREAD

**Issue by ghost** [jasonlewis/basset#98]
Just a little micro-optimization to save a few bytes in the HTML. In HTML5 the script tag is assumed to be javascript, so this doesn't need to be specified. The page still validates too.

As an example, Google's CDN doesn't specify the type for their script tags either: https://developers.google.com/speed/libraries/devguide#jquery

**Comment by jasonlewis** [comment]
Yeah it's been removed already! Thanks. :smile:
